{
 "title": "Overview",
 "description": "Satisfactory Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "server", "query": { "query": "label_values(url)" } },
   {
    "name": "session",
    "query": {
     "query": "label_values({url=\"$server\"},session_name)"
    }
   },
   {
    "name": "circuit",
    "query": {
     "query": "{circuit_id=~\".+\",url=~\"$server\",session_name=~\"$session\"}"
    }
   },
   {
    "name": "player",
    "query": "SELECT data ->> 'Name' as NAME FROM cache where metric = 'player' and url = '$server' and session_name = '$session';"
   },
   {
    "name": "vehicle",
    "label": "Vehicle",
    "query": "select\ndata->>'ID' as __value,\nconcat(data->>'ID', ' (', data ->> 'Name', ':', data ->> 'PathName',')') as __text\nfrom cache where metric = 'truck'\nand url = '$server'\nand session_name = '$session'\norder by id desc;"
   },
   {
    "name": "item",
    "query": {
     "query": "label_values(item_production_capacity_per_min,item_name)"
    }
   },
   {
    "name": "item_storage",
    "label": "Storage Item",
    "query": "select \ndata ->> 'Name' as name\nfrom cache where metric = 'worldInv'\nand url = '$server'\nand session_name = '$session';"
   },
   {
    "name": "item_efficiency",
    "label": "Efficiency Item",
    "query": {
     "query": "label_values(item_production_capacity_per_min{url=\"$server\", session_name=\"$session\"},item_name)"
    }
   },
   {
    "name": "train",
    "label": "Train name",
    "query": "select\ndata ->> 'Name'\nfrom cache_with_history c\nwhere metric = 'train'\nand url = '$server'\nand session_name = '$session'\norder by c.id desc"
   },
   {
    "name": "drone",
    "label": "Drone ID",
    "query": "select\ndata ->> 'ID' as __value,\nconcat(data ->> 'ID', ' : ', data ->> 'HomeStation') as __text\nfrom cache c\nwhere metric = 'drone'\nand data ->> 'CurrentFlyingMode' <> 'DFM_None'\nand url = '$server'\nand session_name = '$session'\norder by c.id desc"
   },
   { "name": "xmin", "label": "x min", "query": "-3750" },
   { "name": "xmax", "label": "x max", "query": "3750" },
   { "name": "ymax", "label": "y max", "query": "4910" },
   { "name": "ymin", "label": "y min", "query": "-3750" },
   { "name": "percent", "label": "Percent Filter", "query": "100" }
  ]
 },
 "panels": [
  { "title": "Players", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Player position",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\ndata ->> 'Name' as playername,\ndata ->> 'Online' as online,\ndata ->> 'Dead' as dead,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(data -> 'location' ->> 'rotation')::NUMERIC as rotation,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache where metric = 'player'\nand data ->> 'Online' = 'true'\nand data ->> 'Dead' = 'false'\nand url = '$server'\nand session_name = '$session'"
    },
    {
     "rawSql": "SELECT\ndata ->> 'Name' as playername,\ndata ->> 'Online' as online,\ndata ->> 'Dead' as dead,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache where metric = 'player'\nand data ->> 'Online' = 'true'\nand data ->> 'Dead' = 'true'\nand url = '$server'\nand session_name = '$session'"
    },
    {
     "rawSql": "SELECT\ndata ->> 'Name' as playername,\ndata ->> 'Online' as online,\ndata ->> 'Dead' as dead,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache where metric = 'player'\nand data ->> 'Online' = 'false'\nand url = '$server'\nand session_name = '$session'"
    }
   ]
  },
  { "title": "Inventory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "$player inventory",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "repeat": "player",
   "targets": [
    {
     "rawSql": "SELECT (jsonb_array_elements(data -> 'Inventory') ->> 'Name') as NAME,\n(jsonb_array_elements(data -> 'Inventory') ->> 'Amount') as AMOUNT\n FROM cache where metric = 'player' and data ->> 'Name' in (${player:sqlstring}) and url = '$server' and session_name = '$session';"
    }
   ]
  },
  { "title": "Power Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  { "title": "Power Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 } },
  { "title": "Circuit $circuit Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Fuse",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fuse_triggered{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery charge",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery_percent{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery minutes remaining",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery_seconds_empty{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"} / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery charge rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "mwatth" } },
   "targets": [
    {
     "expr": "battery_differential{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "expr": "power_capacity{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "power_max_consumed{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "power_consumed{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "power_consumed_overhead_or_max_consumed:min6h{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "real_power_consumed_max"
    }
   ]
  },
  {
   "title": "Power Breakdown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(vehicle_station_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Truck Stations"
    },
    {
     "expr": "sum(last_over_time(train_station_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Train Stations"
    },
    {
     "expr": "sum(last_over_time(train_power_circuit_consumed{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Trains"
    },
    {
     "expr": "sum(last_over_time(drone_port_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Drone Ports"
    },
    {
     "expr": "sum(last_over_time(factory_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Factory"
    },
    {
     "expr": "sum(last_over_time(resource_sink_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Sinks"
    },
    {
     "expr": "sum(last_over_time(pump_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Pumps"
    },
    {
     "expr": "sum(last_over_time(extractor_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Extractors"
    },
    {
     "expr": "sum(last_over_time(portal_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Portals"
    },
    {
     "expr": "sum(last_over_time(hypertube_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Hypertubes"
    },
    {
     "expr": "sum(last_over_time(fracking_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Resource Well Pressurizers"
    },
    {
     "expression": "$TOTAL-$DRONE-$TRAIN-$TRAIN_STATION-$VEHICLE_STATION-$FACTORY-$SINK-$PUMPS-$EXTRACTORS-$PORTALS-$HYPERTUBES-$RESOURCE_WELLS",
     "type": "math"
    }
   ]
  },
  {
   "title": "Circuit $circuit map",
   "type": "geomap",
   "description": "Map of where circuit $circuit is operating",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT\ndata ->> 'Name' as building,\ndata ->'PowerInfo' ->> 'CircuitGroupID' as circuit,\ndata ->> 'Recipe' as recipe,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache where metric in ('factory', 'extractor')\nand (data -> 'PowerInfo' ->> 'CircuitGroupID')::numeric = $circuit\nand url = '$server'\nand session_name = '$session'"
    }
   ]
  },
  {
   "title": "Circuit and building counts",
   "type": "table",
   "description": "number of buildings on each circuit",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "select \ndata -> 'PowerInfo' ->> 'CircuitGroupID' as circuit,\ncount(*) as building_count\nfrom cache where metric in ('factory', 'extractor')\nand url = '$server'\nand session_name = '$session'\ngroup by circuit\norder by building_count"
    }
   ]
  },
  {
   "title": "Circuit $circuit Power Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 }
  },
  {
   "title": "Factory Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "expr": "factory_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "factory_power_max{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Vehicle Station Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "expr": "vehicle_station_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "vehicle_station_power_max{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Train Station Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "expr": "train_station_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "train_station_power_max{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Train Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "expr": "train_power_circuit_consumed{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "train_power_circuit_consumed_max{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  { "title": "Production Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 } },
  { "title": "Global Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Current Production",
   "type": "table",
   "description": "Global production",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(prod.name, cons.name) as name,\n  COALESCE(prod.rate, 0) - COALESCE(cons.rate, 0) as rate\nfrom\n  (\n    SELECT\n      t.name,\n      sum(t.val) as rate\n    from\n      (\n        SELECT\n          jsonb_path_query(data, '$.ingredients[*]') ->> 'Name' as name,\n          (\n            (jsonb_path_query(data, '$.ingredients[*]') ->> 'CurrentConsumed') :: NUMERIC\n          ) as val\n        FROM\n          cache\n        where\n          metric in ('factory', 'extractor')\n          and url = '$server'\n          and session_name = '$session'\n      ) as t\n    group by\n      t.name\n    order by\n      t.name\n  ) as cons full\n  outer join (\n    SELECT\n      t.name,\n      sum(t.val) as rate\n    from\n      (\n        SELECT\n          jsonb_path_query(data, '$.production[*]') ->> 'Name' as name,\n          (jsonb_path_query(data, '$.production[*]') ->> 'CurrentProd') :: NUMERIC as val\n        FROM\n          cache\n        where\n          metric in ('factory', 'extractor')\n          and url = '$server'\n          and session_name = '$session'\n      ) as t\n    group by\n      t.name\n    order by\n      t.name\n  ) as prod on cons.name = prod.name\nwhere\n  COALESCE(prod.rate, 0) - COALESCE(cons.rate, 0) != 0\norder by\n  rate desc,\n  name"
    }
   ]
  },
  {
   "title": "Max Production",
   "type": "table",
   "description": "Max global production",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(prod.name, cons.name) as name,\n  COALESCE(prod.rate, 0) - COALESCE(cons.rate, 0) as rate\nfrom\n  (\n    SELECT\n      t.name,\n      sum(t.val) as rate\n    from\n      (\n        SELECT\n          jsonb_path_query(data, '$.ingredients[*]') ->> 'Name' as name,\n          (\n            (jsonb_path_query(data, '$.ingredients[*]') ->> 'MaxConsumed') :: NUMERIC\n          ) val\n        FROM\n          cache\n        where\n          metric in('factory', 'extractor')\n          and url = '$server'\n          and session_name = '$session'\n      ) as t\n    group by\n      t.name\n    order by\n      t.name\n  ) as cons full\n  outer join (\n    SELECT\n      t.name,\n      sum(t.val) as rate\n    from\n      (\n        SELECT\n          jsonb_path_query(data, '$.production[*]') ->> 'Name' as name,\n          (jsonb_path_query(data, '$.production[*]') ->> 'MaxProd') :: NUMERIC val\n        FROM\n          cache\n        where\n          metric in ('factory', 'extractor')\n          and url = '$server'\n          and session_name = '$session'\n      ) as t\n    group by\n      t.name\n    order by\n      t.name\n  ) as prod on cons.name = prod.name\nwhere\n  COALESCE(prod.rate, 0) - COALESCE(cons.rate, 0) != 0\norder by\n  rate desc,\n  name"
    }
   ]
  },
  { "title": "$item Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Production vs consumption /min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "item_production_capacity_per_min{item_name=\"$item\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "items_produced_per_min{item_name=\"$item\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "item_consumption_capacity_per_min{item_name=\"$item\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "items_consumed_per_min{item_name=\"$item\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Production vs consumption %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "item_production_capacity_pc{item_name=\"$item\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "item_consumption_capacity_pc{item_name=\"$item\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Resource Sink", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Sink Points Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(resource_sink_total_points{url=\"$server\", session_name=\"$session\"}[$__rate_interval]) * 60",
     "legendFormat": "{{sink_type}}"
    }
   ]
  },
  {
   "title": "Points to coupon",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resource_sink_points_to_coupon{url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{sink_type}}"
    }
   ]
  },
  {
   "title": "Collected Coupons",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resource_sink_collected_coupons{url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Next coupon",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resource_sink_percent{url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{sink_type}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Storage Map",
   "type": "geomap",
   "description": "Map of storage containers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "rawSql": "select t.name,\nt.inventory,\nt.x,\nt.y,\nt.z,\nt.longitude,\nt.latitude\nfrom (\nselect \ndata ->> 'Name' as name,\ndata -> 'Inventory' as inventory,\nitem ->> 'Name' as item,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache\ncross join jsonb_path_query(data, '$.Inventory[*]') as item where metric = 'storageInv'\nand item->>'Name' = some(array[$item_storage]::text[])\nand url = '$server'\nand session_name = '$session'\n) as t\ngroup by \nt.name,\nt.inventory,\nt.x,\nt.y,\nt.z,\nt.longitude,\nt.latitude\n;"
    }
   ]
  },
  {
   "title": "Cloud storage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "select \ndata ->> 'Name' as name,\n(data ->> 'Amount')::NUMERIC as count\nfrom cache where metric = 'cloudInv'\nand url = '$server'\nand session_name = '$session';"
    }
   ]
  },
  {
   "title": "World storage",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "select \ndata ->> 'Name' as name,\n(data ->> 'Amount')::NUMERIC as count\nfrom cache where metric = 'worldInv'\nand url = '$server'\nand session_name = '$session';"
    }
   ]
  },
  { "title": "Drop Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "Unlooted drop pods",
   "type": "table",
   "description": "List of drop pods remaining",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 126 },
   "targets": [
    {
     "rawSql": "select \n(data -> 'RequiredItem' ->> 'Name') as repair_item,\n(data -> 'RequiredItem' ->> 'Amount') as repair_item_amount,\n(data ->> 'RequiredPower') as power_required,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z\nfrom cache where metric = 'dropPod'\nand data ->> 'Looted' != 'true'\nand url = '$server'\nand session_name = '$session'\norder by x, y;"
    }
   ]
  },
  {
   "title": "Drop Pods Map",
   "type": "geomap",
   "description": "Map of drop pods",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 133 },
   "targets": [
    {
     "rawSql": "select \ndata ->> 'Looted' as looted,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude,\n(data -> 'RequiredItem' ->> 'Name') as repair_item,\n(data -> 'RequiredItem' ->> 'Amount') as repair_item_amount,\n(data ->> 'RequiredPower') as power_required\nfrom cache where metric = 'dropPod'\nand data ->> 'Looted' != 'true'\nand url = '$server'\nand session_name = '$session';"
    },
    {
     "rawSql": "select \ndata ->> 'Looted' as looted,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude,\n(data -> 'RequiredItem' ->> 'Name') as repair_item,\n(data -> 'RequiredItem' ->> 'Amount') as repair_item_amount,\n(data ->> 'RequiredPower') as power_required\nfrom cache where metric = 'dropPod'\nand data ->> 'Looted' = 'true'\nand url = '$server'\nand session_name = '$session';"
    }
   ]
  },
  { "title": "Vehicles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 } },
  {
   "title": "Truck Routes",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
   "targets": [
    {
     "rawSql": "select\nconcat(data->>'ID',':',data->>'VehicleType') as vehicle,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(data -> 'location' ->> 'rotation')::NUMERIC as rotation,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache where metric = 'truck'\nand data ->> 'ID' = '$vehicle'\nand url = '$server'\nand session_name = '$session';"
    },
    {
     "rawSql": "select\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(data -> 'location' ->> 'rotation') as rotation,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache_with_history where metric = 'truck'\nand data ->> 'ID' = '$vehicle'\nand $__timeFilter(time)\nand url = '$server'\nand session_name = '$session'\norder by time desc\nlimit 100;"
    },
    {
     "rawSql": "select\ndata,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(data -> 'location' ->> 'rotation')::NUMERIC as rotation,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache where metric = 'truckStation'\nand url = '$server'\nand session_name = '$session'\nlimit 100;"
    },
    {
     "rawSql": "select\nconcat(data->>'ID',':',data->>'VehicleType') as vehicle,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(data -> 'location' ->> 'rotation')::NUMERIC as rotation,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache where metric = 'truck'\nand data ->> 'ID' <> '$vehicle'\nand url = '$server'\nand session_name = '$session'\norder by id desc"
    }
   ]
  },
  {
   "title": "Vehicle list",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
   "targets": [
    {
     "rawSql": "SELECT\ndata->>'ID' as id,\ndata->>'Name' as type,\ndata->>'PathName' as path_name,\ndata->>'Autopilot' as autopilot,\ndata->>'Status' as status\nfrom cache WHERE metric = 'truck'\nand url = '$server'\nand session_name = '$session';"
    }
   ]
  },
  { "title": "Vehicle Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 } },
  {
   "title": "Fuel Loadout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "vehicle_fuel{vehicle_type!=\"Factory Cart™\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{id}} ({{vehicle_type}}) - {{fuel_type}}"
    }
   ]
  },
  {
   "title": "Vehicle Round trip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "expr": "vehicle_round_trip_seconds{url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{id}} ({{vehicle_type}}) - {{path_name}}"
    }
   ]
  },
  { "title": "Trains", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 164 } },
  {
   "title": "Train Routes",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 165 },
   "targets": [
    {
     "rawSql": "select\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(data -> 'location' ->> 'rotation')::NUMERIC as rotation,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache_with_history where metric = 'train'\nand data ->> 'Name' = '$train'\nand $__timeFilter(time)\nand url = '$server'\nand session_name = '$session'\norder by time desc\nlimit 720;"
    },
    {
     "rawSql": "select\ndata->>'Name' as name,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(data -> 'location' ->> 'rotation')::NUMERIC as rotation,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache where metric = 'train'\nand data ->> 'Name' = '$train'\nand url = '$server'\nand session_name = '$session'\norder by id desc;"
    },
    {
     "rawSql": "select\n  data ->> 'Name' as station_name,\n  (data -> 'location' ->> 'x') :: NUMERIC / 100 as x,\n  (data -> 'location' ->> 'y') :: NUMERIC / 100 as y,\n  (data -> 'location' ->> 'z') :: NUMERIC / 100 as z,\n  (data -> 'location' ->> 'rotation') :: NUMERIC as rotation,\n  (((data -> 'location' ->> 'x') :: NUMERIC + 375000) * 0.0000001015) as longitude,\n  (((data -> 'location' ->> 'y') :: NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache\nwhere metric = 'trainStation'\n  and url = '$server'\n  and session_name = '$session'\n  and (data -> 'Name') <@ (select jsonb_path_query_array(data, '$.TimeTable[*].StationName') from cache c where metric = 'train' and data ->> 'Name' = '$train' and url = '$server' and session_name = '$session' limit 1)"
    },
    {
     "rawSql": "select\ndata->>'Name' as name,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(data -> 'location' ->> 'rotation')::NUMERIC as rotation,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache where metric = 'train'\nand data ->> 'Name' <> '$train'\nand url = '$server'\nand session_name = '$session'\norder by id desc;"
    },
    {
     "rawSql": "select\n  data ->> 'Name' as station_name,\n  (data -> 'location' ->> 'x') :: NUMERIC / 100 as x,\n  (data -> 'location' ->> 'y') :: NUMERIC / 100 as y,\n  (data -> 'location' ->> 'z') :: NUMERIC / 100 as z,\n  (data -> 'location' ->> 'rotation') :: NUMERIC as rotation,\n  (((data -> 'location' ->> 'x') :: NUMERIC + 375000) * 0.0000001015) as longitude,\n  (((data -> 'location' ->> 'y') :: NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache\nwhere metric = 'trainStation'\n  and url = '$server'\n  and session_name = '$session'\n  and not (data -> 'Name') <@ (select jsonb_path_query_array(data, '$.TimeTable[*].StationName') from cache c where metric = 'train' and data ->> 'Name' = '$train' and url = '$server' and session_name = '$session' limit 1)"
    }
   ]
  },
  {
   "title": "Next stop",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 165 },
   "targets": [
    {
     "rawSql": "select\ndata->>'TrainStation' as name\nfrom cache where metric = 'train'\nand data ->> 'Name' = '$train'\nand url = '$server'\nand session_name = '$session'\norder by id desc;"
    }
   ]
  },
  {
   "title": "$train timetable",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 168 },
   "targets": [
    {
     "rawSql": "select\n  jsonb_array_elements_text(jsonb_path_query_array(data, '$.TimeTable[*].StationName')) as station\nfrom cache c\nwhere metric = 'train'\n  and data ->> 'Name' = '$train'\n  and url = '$server'\n  and session_name = '$session'"
    }
   ]
  },
  { "title": "All Train Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 174 } },
  {
   "title": "Train Round trip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "expr": "train_round_trip_seconds{url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Train list",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 175 },
   "targets": [
    {
     "rawSql": "SELECT \ndata->>'Name' as name,\ndata->>'Status' as status,\ndata->>'TrainStation' as next_station,\nstring_agg(t.timetable,', ') as timetable\nfrom cache c\njoin (select id, jsonb_array_elements_text(jsonb_path_query_array(data, '$.TimeTable[*].StationName')) as timetable from cache where metric='train' and url = '$server' and session_name = '$session') as t on t.id = c.id\nwhere metric = 'train'\nand url = '$server'\nand session_name = '$session'\ngroup by data->>'Name', data->>'Status', data->>'TrainStation';"
    }
   ]
  },
  {
   "title": "Train power consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "expr": "train_power_consumed{name=\"$train\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{name}} power use"
    }
   ]
  },
  {
   "title": "Station Travel Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "expr": "avg by(from, to) (train_segment_trip_seconds{url=\"$server\", session_name=\"$session\"})",
     "legendFormat": "{{from}} -> {{to}}"
    }
   ]
  },
  { "title": "Derail Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 191 } },
  { "title": "Drones", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 199 } },
  {
   "title": "Drone Routes",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
   "targets": [
    {
     "rawSql": "select\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(data -> 'location' ->> 'rotation')::NUMERIC as rotation,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache_with_history where metric = 'drone'\nand data ->> 'ID' = '$drone'\nand $__timeFilter(time)\nand url = '$server'\nand session_name = '$session'\norder by time desc\nlimit 100;\n"
    },
    {
     "rawSql": "select\ndata ->> 'HomeStation' as name,\ndata ->> 'ID' as id,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(data -> 'location' ->> 'rotation')::NUMERIC as rotation,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache where metric = 'drone'\nand data ->> 'ID' = '$drone'\nand url = '$server'\nand session_name = '$session'\norder by id desc;\n"
    },
    {
     "rawSql": "(select\n    data ->> 'Name' as name,\n    data ->> 'PairedStation' as paired,\n    (data -> 'location' ->> 'x') :: NUMERIC / 100 as x,\n    (data -> 'location' ->> 'y') :: NUMERIC / 100 as y,\n    (data -> 'location' ->> 'z') :: NUMERIC / 100 as z,\n    (data -> 'location' ->> 'rotation') :: NUMERIC as rotation,\n    (\n      ((data -> 'location' ->> 'x') :: NUMERIC + 375000) * 0.0000001015\n    ) as longitude,\n    (\n      ((data -> 'location' ->> 'y') :: NUMERIC + 375000) * -0.0000001172\n    ) as latitude\n  from\n    cache\n  where\n    metric = 'droneStation'\n    and url = '$server'\n    and session_name = '$session'\n    and (data -> 'Name' <@\n(\n  select\n    jsonb_build_array(data -> 'Name',\n    data -> 'PairedStation')\n  from\n    cache\n    join (\n      SELECT\n        data ->> 'HomeStation' as home_station\n      from\n        cache\n      where\n        metric = 'drone'\n        and data ->> 'ID' = '$drone'\n        and url = '$server'\n        and session_name = '$session'\n    ) as drones on drones.home_station = data ->> 'Name'\n  where\n    metric = 'droneStation'\n    and url = '$server'\n    and session_name = '$session'\n    limit 1\n)\n)\n)"
    },
    {
     "rawSql": "select\ndata ->> 'HomeStation' as name,\ndata ->> 'ID' as id,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(data -> 'location' ->> 'rotation')::NUMERIC as rotation,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache where metric = 'drone'\nand data ->> 'ID' <> '$drone'\nand url = '$server'\nand session_name = '$session'\norder by id desc;\n"
    },
    {
     "rawSql": "(select\n    data ->> 'Name' as name,\n    data ->> 'PairedStation' as paired,\n    (data -> 'location' ->> 'x') :: NUMERIC / 100 as x,\n    (data -> 'location' ->> 'y') :: NUMERIC / 100 as y,\n    (data -> 'location' ->> 'z') :: NUMERIC / 100 as z,\n    (data -> 'location' ->> 'rotation') :: NUMERIC as rotation,\n    (\n      ((data -> 'location' ->> 'x') :: NUMERIC + 375000) * 0.0000001015\n    ) as longitude,\n    (\n      ((data -> 'location' ->> 'y') :: NUMERIC + 375000) * -0.0000001172\n    ) as latitude\n  from\n    cache\n  where\n    metric = 'droneStation'\n    and url = '$server'\n    and session_name = '$session'\n    and NOT(data -> 'Name' <@\n(\n  select\n    jsonb_build_array(data -> 'HomeStation',\n    data -> 'PairedStation')\n  from\n    cache\n    join (\n      SELECT\n        data ->> 'HomeStation' as home_station\n      from\n        cache\n      where\n        metric = 'drone'\n        and data ->> 'ID' = '$drone'\n        and url = '$server'\n        and session_name = '$session'\n    ) as drones on drones.home_station = data ->> 'Name'\n  where\n    metric = 'droneStation'\n    and url = '$server'\n    and session_name = '$session'\n    limit 1\n)\n)\n)"
    }
   ]
  },
  {
   "title": "Drone list",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 200 },
   "targets": [
    {
     "rawSql": "select data ->> 'Name' as drone_port,\ndata ->> 'PairedStation' as paired_port,\ncoalesce(drones.id, '(no drone)') as drone_id\nfrom\ncache\nleft join\n(SELECT \ndata ->> 'HomeStation' as home_station,\ndata ->> 'ID' as id,\ndata ->> 'CurrentFlyingMode' as flying_mode\nfrom cache\nwhere metric = 'drone'\nand url = '$server'\nand session_name = '$session'\n) as drones on drones.home_station = data ->> 'Name'\nwhere metric = 'droneStation'\nand url = '$server'\nand session_name = '$session'\norder by drones.id"
    }
   ]
  },
  { "title": "Drone Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 208 } },
  {
   "title": "Drone Round Trip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "expr": "drone_port_round_trip_seconds{url=\"$server\", session_name=\"$session\"} / 60 > 0",
     "legendFormat": "{{home_station}}"
    }
   ]
  },
  {
   "title": "Fuel Consumption Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "fuel/min" } },
   "targets": [
    {
     "expr": "drone_port_fuel_rate{url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{home_station}} - {{fuel_name}}"
    }
   ]
  },
  { "title": "Factory Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 217 } },
  {
   "title": "Factory production calculator by region",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 218 },
   "options": {
    "content": "Calculate input and output by a square region, bounded by variables.\n\nEdit the map displayed and inspect buildings to get approximate x + y coordinates.\nThen plugin bounds for x and y. Factory exports (+/min) and imports (-/min) will be updated according to the new area.\n\nx min, x max, y min and y max are ingame coordinates."
   }
  },
  { "title": "Factory details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 223 } },
  {
   "title": "Factory Map",
   "type": "geomap",
   "description": "Approximate map of the factory - useful for plotting factory boundaries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 224 },
   "targets": [
    {
     "rawSql": "SELECT\ndata ->> 'Recipe' as recipe,\ndata ->> 'Name' as building,\ndata,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nFROM cache\nwhere metric in ('factory', 'extractor')\nand (data -> 'location' ->> 'x')::NUMERIC/100 >= $xmin\nand (data -> 'location' ->> 'x')::NUMERIC/100 <= $xmax \nand (data -> 'location' ->> 'y')::NUMERIC/100 >= $ymin\nand (data -> 'location' ->> 'y')::NUMERIC/100 <= $ymax\nand url = '$server'\nand session_name = '$session'"
    },
    {
     "rawSql": "SELECT\n  data ->> 'Recipe' as recipe,\n  data ->> 'building' as building,\n  (data -> 'location' ->> 'x') :: NUMERIC / 100 as x,\n  (data -> 'location' ->> 'y') :: NUMERIC / 100 as y,\n  (data -> 'location' ->> 'z') :: NUMERIC / 100 as z,\n  (\n    ((data -> 'location' ->> 'x') :: NUMERIC + 375000) * 0.0000001015\n  ) as longitude,\n  (\n    ((data -> 'location' ->> 'y') :: NUMERIC + 375000) * -0.0000001172\n  ) as latitude\nFROM\n  cache\nwhere\n  metric in ('factory', 'extractor')\n  and (\n    (data -> 'location' ->> 'x') :: NUMERIC / 100 < $xmin\n    or (data -> 'location' ->> 'x') :: NUMERIC / 100 > $xmax\n    or (data -> 'location' ->> 'y') :: NUMERIC / 100 < $ymin\n    or (data -> 'location' ->> 'y') :: NUMERIC / 100 > $ymax\n  )\n  and url = '$server'\n  and session_name = '$session'"
    },
    {
     "rawSql": "(\n  select\n    id,\n    x,\n    y,\n    ((x * 100 + 375000) * 0.0000001015) as longitude,\n    ((y * 100 + 375000) * -0.0000001172) as latitude\n  from\n    (\n      values\n(1, $xmin, $ymin),\n        (2, $xmax, $ymin),\n        (3, $xmax, $ymax),\n        (4, $xmin, $ymax),\n        (5, $xmin, $ymin)\n    ) as coords (id, x, y)\n)\norder by\n  id"
    }
   ]
  },
  {
   "title": "Selected buildings and recipes",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 224 },
   "targets": [
    {
     "rawSql": "SELECT\ndata ->> 'Recipe' as recipe,\ndata ->> 'Name' as building,\ndata ->> 'ManuSpeed' as clockspeed,\ncount(*) as count\nFROM cache\nwhere metric in ('factory', 'extractor')\nand (data -> 'location' ->> 'x')::NUMERIC/100 >= $xmin\nand (data -> 'location' ->> 'x')::NUMERIC/100 <= $xmax \nand (data -> 'location' ->> 'y')::NUMERIC/100 >= $ymin\nand (data -> 'location' ->> 'y')::NUMERIC/100 <= $ymax\nand url = '$server'\nand session_name = '$session'\ngroup by recipe, building, clockspeed"
    }
   ]
  },
  {
   "title": "Current average Production",
   "type": "table",
   "description": "Current average production(+) and consumption(-) over the selected time period",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 238 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(prod.name, cons.name) as name,\n  COALESCE(prod.rate, 0) - COALESCE(cons.rate, 0) as rate\nfrom\n  (\n    select\n      t.name,\n      avg(t.rate) as rate\n    from\n      (\n        SELECT\n          t.name,\n          sum(t.val) as rate\n        from\n          (\n            SELECT\n              time,\n              jsonb_path_query(data, '$.ingredients[*]') ->> 'Name' as name,\n              (\n                (\n                  jsonb_path_query(data, '$.ingredients[*]') ->> 'CurrentConsumed'\n                ) :: NUMERIC\n              ) val\n            FROM\n              cache_with_history\n            where\n              metric in ('factory', 'extractor')\n              AND (data -> 'location' ->> 'x') :: NUMERIC BETWEEN ($xmin * 100)\n              and ($xmax * 100)\n              AND (data -> 'location' ->> 'y') :: NUMERIC BETWEEN ($ymin * 100)\n              and ($ymax * 100)\n              and $__timeFilter(time) \n              and url = '$server'\n              and session_name = '$session'\n          ) as t\n        group by\n          t.name,\n          t.time\n        order by\n          t.name\n      ) as t\n    group by\n      t.name\n  ) as cons full\n  outer join (\n    select\n      t.name,\n      avg(t.rate) as rate\n    from\n      (\n        SELECT\n          t.name,\n          sum(t.val) as rate\n        from\n          (\n            SELECT\n              time,\n              jsonb_path_query(data, '$.production[*]') ->> 'Name' as name,\n              (\n                jsonb_path_query(data, '$.production[*]') ->> 'CurrentProd'\n              ) :: NUMERIC val\n            FROM\n              cache_with_history\n            where\n              metric in ('factory', 'extractor')\n              AND (data -> 'location' ->> 'x') :: NUMERIC BETWEEN ($xmin * 100)\n              and ($xmax * 100)\n              AND (data -> 'location' ->> 'y') :: NUMERIC BETWEEN ($ymin * 100)\n              and ($ymax * 100)\n              and $__timeFilter(time) \n              and url = '$server'\n              and session_name = '$session'\n          ) as t\n        group by\n          t.name,\n          t.time\n        order by\n          t.name\n      ) as t\n    group by\n      t.name\n  ) as prod on cons.name = prod.name\nwhere\n  COALESCE(prod.rate, 0) - COALESCE(cons.rate, 0) != 0\norder by\n  rate desc,\n  name\n"
    }
   ]
  },
  {
   "title": "Max Production",
   "type": "table",
   "description": "Maximum production(+) and consumption(-)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 238 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(prod.name, cons.name) as name,\n  COALESCE(prod.rate, 0) - COALESCE(cons.rate, 0) as rate\nfrom\n  (\n    SELECT\n      t.name,\n      sum(t.val) as rate\n    from\n      (\n        SELECT\n          jsonb_path_query(data, '$.ingredients[*]') ->> 'Name' as name,\n          (\n            (jsonb_path_query(data, '$.ingredients[*]') ->> 'MaxConsumed') :: NUMERIC\n          ) val\n        FROM\n          cache\n        where\n          metric in ('factory', 'extractor')\n          AND (data -> 'location' ->> 'x') :: NUMERIC BETWEEN ($xmin * 100)\n          and ($xmax * 100)\n          AND (data -> 'location' ->> 'y') :: NUMERIC BETWEEN ($ymin * 100)\n          and ($ymax * 100)\n          and url = '$server'\n          and session_name = '$session'\n      ) as t\n    group by\n      t.name\n  ) as cons full\n  outer join (\n    SELECT\n      t.name,\n      sum(t.val) as rate\n    from\n      (\n        SELECT\n          jsonb_path_query(data, '$.production[*]') ->> 'Name' as name,\n          (jsonb_path_query(data, '$.production[*]') ->> 'MaxProd') :: NUMERIC val\n        FROM\n          cache\n        where\n          metric in ('factory', 'extractor')\n          AND (data -> 'location' ->> 'x') :: NUMERIC BETWEEN ($xmin * 100)\n          and ($xmax * 100)\n          AND (data -> 'location' ->> 'y') :: NUMERIC BETWEEN ($ymin * 100)\n          and ($ymax * 100)\n          and url = '$server'\n          and session_name = '$session'\n      ) as t\n    group by\n      t.name\n  ) as prod on cons.name = prod.name\nwhere\n  COALESCE(prod.rate, 0) - COALESCE(cons.rate, 0) != 0\norder by\n  rate desc,\n  name"
    }
   ]
  },
  { "title": "Efficiency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 247 } },
  {
   "title": "Efficiency Map",
   "type": "geomap",
   "description": "Search for buildings by item production name, and filter out for buildings that are underperforming.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 248 },
   "targets": [
    {
     "rawSql": "SELECT\ndata ->> 'Name' as building,\ndata ->> 'Recipe' as recipe,\n(data -> 'production' -> 0 ->> 'ProdPercent')::NUMERIC as percent,\ndata,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nFROM cache\nwhere metric in ('factory', 'extractor')\nand (data -> 'production' -> 0 ->> 'ProdPercent')::NUMERIC <= $percent\nand data -> 'production' -> 0 ->> 'Name' in($item_efficiency)\nand url = '$server'\nand session_name = '$session'"
    }
   ]
  }
 ]
}