apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servarr

resources:
- network-policy.yaml
- namespace.yaml
- deployments.yaml
- torrent-sops-all.yaml
- services-sops-all.yaml
- routes.yaml
- nordvpn-sops.yaml
