apiVersion: ENC[AES256_GCM,data:TAwtVLiAjQ==,iv:KftYWWZmDIXd13e/Wp1rKaUERIYr5lmacPqtFN3zRx0=,tag:BlAfMW5qqXVplZaAjJN0HQ==,type:str]
kind: ENC[AES256_GCM,data:9iQ5/A8m2VknCA==,iv:TgrVszkGngH0O2vpKWWba6ry1sZO89pGFZix0pEx2/g=,tag:FZDytBYlNZiVPevefppnmQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WUcDlQGdluB8eDb/xQ==,iv:Q4ECj/JHCo7+FiwpJp6og9txy/tziSssu7kUVIFAF+A=,tag:oPJuVUji4Jf8UMnN5q1kzw==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:GQ==,iv:tSVbw7DdINCJ9yHi0IL7sWBS7CrluiXAxaNaBEtL3iE=,tag:AS9gns7oxiMnxOzLZ2AEbw==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:lv1Zb2OpuhEkYzUO6A==,iv:n2gh9eh0m6AQ0a7FBnRpkAye8E0oPXqJefZan+eWfUA=,tag:1wxdt5pBCWX2f9RNbYpHsQ==,type:str]
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:a2K/LeZZbK5WC+VeZA==,iv:ZGph6E7Q6Dq/BpxpAA02CtD+nowePPJC/tgDk9XtRGk=,tag:k0fKC8DSeUuodO1TOR+CBQ==,type:str]
        spec:
            nodeSelector:
                location: ENC[AES256_GCM,data:YVZ/uc4=,iv:H4EzwPCiYG+k8sJX+G+7FUI+zC5GyD6s3/stIUmCnUI=,tag:fISYkbkKcWrmrJZ84iAJFg==,type:str]
            tolerations:
                - key: ENC[AES256_GCM,data:y1XAQJ6qwKYJ6PQ=,iv:plSjVCSYDmTj4vW820S6Sg3F6SOvKv/NyizNvKdFmqA=,tag:lvZiTfiMrbDIRgODq+GTgw==,type:str]
                  operator: ENC[AES256_GCM,data:LjNWy9Q=,iv:qkFke6wfbc//pgPSIRKdlzHIaNkTBAZ9VicLo4163O4=,tag:2uwlDOA4QmawlKb2+Bkhmw==,type:str]
                  value: ENC[AES256_GCM,data:TP7ddhM=,iv:FY0+zQVAKSW4yGdPg0E0e+G8K/FW08U8zkj2OhIS0GM=,tag:OT/cr++exdXxJho8mNR8Cw==,type:str]
            containers:
                - name: ENC[AES256_GCM,data:ILRDpiqOiA==,iv:n4x+/VgD7dcYmkBqTbFEOGe/doj+9P6fkLhhUfChrnw=,tag:O4KW7uPrXiq1UQ+Bp/WFsQ==,type:str]
                  image: ENC[AES256_GCM,data:vFIX0e0bS/0ZE0SpxL5z8TQ=,iv:lKMusoqiW0zr1iCw25KOuWjYy4oVcf5f1jAsnHaYTYU=,tag:IGdC1Z6KNDP+RUzDnT1g5A==,type:str]
                  securityContext:
                    capabilities:
                        add:
                            - ENC[AES256_GCM,data:s3NwMRC8KY+u,iv:iKxwfYbGTU041nibGiTCmEg0AFOsyLteMuZWqN1kbg4=,tag:YwHNlo2Ao7gQD8hKVLSd8g==,type:str]
                  env:
                    - name: ENC[AES256_GCM,data:cdPpPygG+g==,iv:P7SAG7OYJ4ajTBqvkcC4uDnP1gvwnxkuFJhB+Gq9s0o=,tag:8udeFeSN55VSocLgf33nIQ==,type:str]
                      value: ENC[AES256_GCM,data:IjNGgf1o0V7r,iv:VcsWrLBIK02Sf4FezZKjwjZNDlY20nb/NWIkhNjisDU=,tag:en2TZDYPwUTkd0tr3S2mVg==,type:str]
                    - name: ENC[AES256_GCM,data:Nh5vw4lnJ3yFFNxbpZqXv7yHXSo=,iv:iY6x+RPCmcv+vwgBg6yFYwQYV++o/F1anLthQH/6Oig=,tag:cgIfXwn346F67axjRCoa+A==,type:str]
                      value: ENC[AES256_GCM,data:yDM5Wn30MNrbUPvo7VM=,iv:+lHNGO1bil9Zr0QWAod4tVw7X84wYmx7jz9qc5m96aY=,tag:Sv5Bj5ncVT/yMGY0Wy/q7Q==,type:str]
                    - name: ENC[AES256_GCM,data:I+HVKhX5RE9HiR4=,iv:ZLMEnyd+VYpg+SPVISf3CBe/IfR5ZSRz9lgwwCkxEVQ=,tag:ETm+sGqd6PMNVhkupZ7s0g==,type:str]
                      value: ENC[AES256_GCM,data:2WzxDAdRhQ==,iv:LAkTNk8eUQ+Yii9QbBEJiUBPIrh/wV25taSJZZyr2ys=,tag:+fAurW7VG8NemTiS0zQZwg==,type:str]
                    - name: ENC[AES256_GCM,data:QcKNg9jlWXHq,iv:Mm19Nyz+/qfO4Sljv1tAgWiaxaXkZ2wf6fjwoaW7AeM=,tag:kGQQxiYcGspysWUxhkL4Ig==,type:str]
                      value: ENC[AES256_GCM,data:Qbcf,iv:MQ2qljfZVhcxbWftKr28HHqPPSS8ByQr9JReQSMXsNk=,tag:S4j5Ug/WQu/Lh2kCVsfKdQ==,type:str]
                    - name: ENC[AES256_GCM,data:QBinUT4jtwGtZs/ARym1A59pFRgBsJitgw==,iv:8KvMhtmfZOPIS44c+qd8Cq7bgUrGzDHAZRxdZH7jx8Y=,tag:ZKFB/o8HVjEd5xA7gb1/Rw==,type:str]
                      value: ENC[AES256_GCM,data:uhWELBSBL1sgIGyxjZ00y0dI0OXQQg97KD8xrbCoDEakOMOq,iv:2FqmKRwsdM3kPG9SHgx+pFygG2Bm4kAZQpdH9pqwWhM=,tag:KCvTNGN8Z9PzWGFs84+WrQ==,type:str]
                    - name: ENC[AES256_GCM,data:mWN0pI8TWsPU+bKfHaUQ7QdtFmOlOMgSn/IC,iv:yWIRXbHwp4xJIa+Tiil4Y9D2JiZCR3y9zvnA5jpsg9s=,tag:jGGoU//AI2xEZWH5StVDBA==,type:str]
                      value: ENC[AES256_GCM,data:xTEl1+k=,iv:spboEWnS6qJS1P70/uvs1qLz5UD9cDi9nz8ejkeFBUQ=,tag:lYrqz8NFa+/DVxFu+SpEQA==,type:str]
                    - name: ENC[AES256_GCM,data:MqKI89O4oX+R3vTbEDzvEFk=,iv:OBJhWe50oBrrQfuvRYALoNDTdi5D2JWEFNlK7qjLPgk=,tag:WsRtvSels9hBaGATKBSDAA==,type:str]
                      value: ENC[AES256_GCM,data:Fpeytw==,iv:Xb8ECRplbErb3F0pNkz0mJEUDmRIlRLJVQKePbgcBC4=,tag:bmOtx6F310xRo6hi6N5oFQ==,type:str]
                    - name: ENC[AES256_GCM,data:hc7weLUu62A+Fr59k1cjwixBxug=,iv:1RRQm5ufTLcaRuBwuu+9p+lX0pZurbXEhBnE3z7hAOA=,tag:i0mE6XRkJCVy3cM725nl1A==,type:str]
                      value: ENC[AES256_GCM,data:djFkhugFWQ==,iv:jI2nGhazCyKa4/FoDa+A6jYAJGDr82wlBbzjJAvaX64=,tag:0iNnWjfUORgfRzLSUoABBg==,type:str]
                    - name: ENC[AES256_GCM,data:bT45BjleZRo=,iv:cceXyZN0+364vWJklKCvq8YuXl3Yn8IZ+Ce7oFwo2mQ=,tag:0x1Smh3XiVmElP45E7W3/A==,type:str]
                      #ENC[AES256_GCM,data:LXcoCVJKPiLXy7jq+A==,iv:+q2bWhcmyE8eEcbmAgjEIh1jzMnagkEGjLM7bYfCims=,tag:3DPkpOcVTylpVDNp+DvSgw==,type:comment]
                      value: ENC[AES256_GCM,data:bFyXLJi/yg==,iv:tVX71lvlqHl1omeGAQvM3V9SWyLfLltRIAMnoA3svwA=,tag:P1oDaznDIhrWvM6o4y9RfA==,type:str]
                    - name: ENC[AES256_GCM,data:kzPKPWwyVukabt8V,iv:vGTicWlnF7wz90d+I1LLt5w7lTlKs7KKR0T3Aj+ISEs=,tag:jZBUJSyCElgqCxMVME8T5g==,type:str]
                      valueFrom:
                        secretKeyRef:
                            name: ENC[AES256_GCM,data:cCfzFX1CLXpPlMWjEEg=,iv:/1wufCddgnevzzzpog94ofCvsF1mSRmBZbPbFGGin5E=,tag:nZiJkqWxnSxp437GxTS9cQ==,type:str]
                            key: ENC[AES256_GCM,data:tsjz+xt+dJA=,iv:bu6lZyb3nemJYD1fcAtyAYp1k6s3NpxLenJw5HCoaEA=,tag:4rEF2HwtpNwZ62InYKnn6w==,type:str]
                    - name: ENC[AES256_GCM,data:zdeGYsNaIfs1uJIcXsqFBg==,iv:qqrdAG9S29r99sNcpqti1c2rhVuVMDwr+ZY/kFpUXHA=,tag:NzhXKnsORVgJp7akdBomVQ==,type:str]
                      valueFrom:
                        secretKeyRef:
                            name: ENC[AES256_GCM,data:25YSNHEMqQIgCp1tRss=,iv:nhUAaUvy21dCU7CJy7JvvOIAqxFvIY+SgzHPkFy2iBM=,tag:EkPtP5TPQTsK7tNNd6FQwg==,type:str]
                            key: ENC[AES256_GCM,data:If2ErNEDgPg=,iv:AQQQSqnLT6XfzTH1awkIz+4gu8YrNGxBBGehOYpXkEg=,tag:FJRAsbEPZhsmV6A2YB+pWA==,type:str]
                - name: ENC[AES256_GCM,data:NNeiW361ZtnUAK0=,iv:0dkJUQZxxmgwWCPoJaPc1Pljd8Ktseg+2QP4nj4YrEU=,tag:5AhHypqn11KOH+CDrN0Myw==,type:str]
                  image: ENC[AES256_GCM,data:NBqCeZ8UpKhoYL+2TjnjyXKmI+hCr0DjVe0ZjneA,iv:eQ5M1VqtkndpQEv5XRAgbUBdSzT6meGh2NF4YX25EYA=,tag:Loi7okexW1KC1TKjDR9B2w==,type:str]
                  env:
                    - name: ENC[AES256_GCM,data:lpYvjg==,iv:4SiBYnN6LCIO5Gwa3vbIQagdc1cmw0DBby/vClvt79I=,tag:QM+vt4dMDp4Hzxfs3OVr+g==,type:str]
                      value: ENC[AES256_GCM,data:/6wtrA==,iv:wFMmmHIsPm2OBykh3oW8f7cxsRiVEGFG4SUxRG3UAbo=,tag:+MqJNtV5ZGeuvuOlDm/pYA==,type:str]
                    - name: ENC[AES256_GCM,data:imsTMA==,iv:q1sE/DbwErBkAXyJ/1nbWi17o+BNJMbZM6rnhwQ89QA=,tag:m7VCbH/3n68o/t9WPvaZ6Q==,type:str]
                      value: ENC[AES256_GCM,data:vn/HDg==,iv:QHDU78OKmgZP3P1+0rw70/0U4Ehz7uxCV9OPCiyjZM0=,tag:s1It/vkzobKo5hogN8fiNw==,type:str]
                    - name: ENC[AES256_GCM,data:uFA=,iv:FtGDN0vezaJ8YXvbXfpelbRkBUKIrO5VlgiNa0MGghA=,tag:ArnQNja4f38V6/Ct96uVoQ==,type:str]
                      value: ENC[AES256_GCM,data:tfzqFOVg4DLKVie+,iv:U5Rbv5/zue/ZgpMkZm2/IadvQ5vJQ8Mn43gI3g4P11o=,tag:FMqWRp2qr/ztKurHLZ6Ffw==,type:str]
                    - name: ENC[AES256_GCM,data:yB0ej8H0ZijjkA==,iv:+1zjMpH0KLiNii1c9xNfvP/baSgQf4WPtJ8mj4wI93Q=,tag:ELlUMsBWwIBtCYG1XdD/vQ==,type:str]
                      value: ENC[AES256_GCM,data:qY+G/g==,iv:ePgO/WsJgG2Mr2uDxSUw2H9yUns4WnQHhrZ8KTsJPZ0=,tag:oYbyID0SJhq4oRHfP5NbZw==,type:str]
                  volumeMounts:
                    - name: ENC[AES256_GCM,data:q/wLwvYI1KW0j/s=,iv:aQ/w5m64zm/8AhtIMwmwpx5lx8tCyPl/2+TMWvyPydw=,tag:yekyMcH3AZz6taxc1IAK1A==,type:str]
                      mountPath: ENC[AES256_GCM,data:I+cLudk6Eg==,iv:/yZ6GX6kfV/W3VBLIJRDcvWvyciGaVB0K3IcXIy21bw=,tag:Vzok7PBx07C6nRt6q3O8/g==,type:str]
                    - name: ENC[AES256_GCM,data:cLW1AhG5mNWHhw==,iv:5E2i0gAz3teDCbCnTS4a4SUY7WUcKWnrKPLS+45/B00=,tag:fp5CO+MZSTzcMWtz1X6tkQ==,type:str]
                      mountPath: ENC[AES256_GCM,data:u2ot41Y=,iv:MUKNjFNOxXG3R9pCIuCrLwyaRGRAfNl/OIA+UbMyDHE=,tag:OLz+lk3BGcm4w//WB+sR5Q==,type:str]
                - name: ENC[AES256_GCM,data:FRVS5/Kd6XI=,iv:yRJH9ONAW7/3eqFfRcyQWNgcsxBOmNFjCoOMs85MqrI=,tag:SCKqh/T3CH/1l6kj7cSzhA==,type:str]
                  image: ENC[AES256_GCM,data:k2K4tbZXWzdv2L4YGCqsYccBKamoFxcRhS1rOtgyGS2W,iv:FTs06C5r836uNA/PCPJQwBI7amJ3I09NdBMjEFkeV1w=,tag:1rX9EtxDg/ijW+3bSMr4yA==,type:str]
                  env:
                    - name: ENC[AES256_GCM,data:g6nAcQ==,iv:MUrV1Q54BAhAcep6wt1pEqIFjq4IkHXHJr3dLA9nLEo=,tag:ScQVLI/t1Pvtg/uWE8iwUA==,type:str]
                      value: ENC[AES256_GCM,data:mOfVaw==,iv:HO94jricI+we0A+FhHFoy8sc4zJKz6FgodySw8CwnH4=,tag:2lMkU0DJSTAaDwSGk3VkuQ==,type:str]
                    - name: ENC[AES256_GCM,data:QsbaeQVG2aA=,iv:LLK80eGkFTZI+lck1OT3RFVg4ke6L0hafTl1TI/7r44=,tag:AGeu0rQUVQsMfds4TlYKQg==,type:str]
                      value: ENC[AES256_GCM,data:avY4CA==,iv:p09hvjz4e0kq0DD7O1ciG9v33Yatf96I20GcDgHeH48=,tag:+AeyCJ18oRxTy4b8uXixMQ==,type:str]
                    - name: ENC[AES256_GCM,data:TlhOkw==,iv:U7lXMq8jz1XJFpXmSljIitGShmO1yXeyVFd3oURLLjk=,tag:fPBtYRyLIMItpxKiDvarBA==,type:str]
                      value: ENC[AES256_GCM,data:0HtdLw==,iv:TVUq9nKDOiprXt71VOZdH82QqNhhLGM/xyY/0fvSt3E=,tag:o2icvf9Os7pJMAAJIQ2rPw==,type:str]
                    - name: ENC[AES256_GCM,data:dqoiAw==,iv:6ikXe6vJibQNLxXkIdyNdd+vDZED6ue3BYo2fLwhhAE=,tag:vSTZ5LalBeHRqr05Omv9/g==,type:str]
                      value: ENC[AES256_GCM,data:A6Wb8A==,iv:lfWQhZlXqlq4s8blBh/ISBuQvHnp2OMJgDePihSM944=,tag:QzdaVcEKVGSoWlYKT4iNcQ==,type:str]
                  ports:
                    - containerPort: ENC[AES256_GCM,data:O2hhOA==,iv:f0p6Huirw7QL8UeEKQznFop8WqoeG3LeWkFvLJQk9l8=,tag:Ey54ouUSwxjQHAduGwihLg==,type:int]
                      name: ENC[AES256_GCM,data:2mp2iexcxEp5787Coe8=,iv:d8BEGbJ0CBHC5jE2GT8UXzyYwOzzrQFKIaIvjr2LrRE=,tag:EZ1v7a9kX+HM0nQ8A4S62g==,type:str]
                  volumeMounts:
                    - name: ENC[AES256_GCM,data:ZOAjjLQQpU0bMV+G3A==,iv:1+68VDA2gccioY/rwlnsSrmG7jEAVogR8Mk4+Zu/zso=,tag:C1IQmQZeWAJv3QaEa+dVrQ==,type:str]
                      mountPath: ENC[AES256_GCM,data:BkhOSx0=,iv:SPL6F2RHctqsuF5VLyoB3B98M9DnIfli1o/leAjUUok=,tag:0W/fixTcPF2zDTu+Zm7ajA==,type:str]
                    - name: ENC[AES256_GCM,data:TDhs+PHFZcCdEPxkfw==,iv:TTTetuAOAPJaxcPeUO3qR78BYaXUbtiT5hBq+XJVuaw=,tag:PIS+xyrob/yBeCaco4XKeA==,type:str]
                      mountPath: ENC[AES256_GCM,data:Zx1F1bt2w7Gy,iv:tSv1V8fLhYsZFSPhlNzA53x2VXGb3xTtfRXeXKt5cGk=,tag:iX8iAeCaOzcmTqY5lOcwJA==,type:str]
            volumes:
                - name: ENC[AES256_GCM,data:iFw7IA+CD2cuwfQ=,iv:ACBx+oxxlESgIRy7ava8ft97ph/4zLZ3kYsDF7OAoyA=,tag:9MpFOhqo/L/MYu3TM213Xw==,type:str]
                  hostPath:
                    path: ENC[AES256_GCM,data:pLgA8yt3z0Z2qZ8eYF762zVYudH9BdHftmDL4++Qv00=,iv:q5tOyl5kInvxCx6sj34FIFlwE0hUOV56s98yAWPkWzc=,tag:ULFXYVtyk0YCDktxVprjYQ==,type:str]
                    type: ENC[AES256_GCM,data:FMVaDcYOGwix8K4YIqf/jhM=,iv:hecCC0JJBwpfWA2jNDrMzvOS5bfcnC9+9K/cWstY3vY=,tag:bgS3S82TXZ48D+JiCfFd9g==,type:str]
                - name: ENC[AES256_GCM,data:JRceZM/5JsRE6A==,iv:p1b9FA1iTnPDteCPJOEn0+ytfgLl7YuetgYwqzH4kUw=,tag:kfu5CQAgjezqo0i3F0EQEg==,type:str]
                  hostPath:
                    path: ENC[AES256_GCM,data:80QmUtX6PCCrOVzyng==,iv:cpWrSmshJ88wPGuYjima+rDynjzd0Y3KRo5QQ/DH+Us=,tag:gW9x6UkSoliK27gmVWmviw==,type:str]
                    type: ENC[AES256_GCM,data:KMFswfLheHF9,iv:wTbl0R6+9FZV3IhQhHPwCthuS6epyaWydl+YsoZ3ePY=,tag:+To0Xcdf0L0Y85LHVjFjgQ==,type:str]
                - name: ENC[AES256_GCM,data:RL+cxQrZUpkNOO5Zwg==,iv:kUNyBnUj4y62PNnYIjvZcbyot7Uc/arehhukCcQguVE=,tag:T0natv98tWnH7ZceTXmF8A==,type:str]
                  hostPath:
                    path: ENC[AES256_GCM,data:6ZaWXXiVi/n01BqrsHTaComt8ZdFuzgr6gBd93M=,iv:S+Rz7dAPzNGNCKNKEkev+3oRsJd5UIB3TNXOi1k5PwU=,tag:07cnsVal1iq1SOg6oO+J4Q==,type:str]
                    type: ENC[AES256_GCM,data:TBtsUclqNtNoonba7zvdl0U=,iv:G6UZYWCsoIh0OeVxQGbbXUOHnSZ89PPj7Ja2FNAuCdk=,tag:x14TiFTNOycouatIeLthYA==,type:str]
                - name: ENC[AES256_GCM,data:K+nX6Uuf6WH6QNue4Q==,iv:f7ooJNshUhcvkBwt0bjp6nG5pEs+wOIGnnP9hQsZxAE=,tag:gYjo8WrFVvuWkzhbBDPR5A==,type:str]
                  hostPath:
                    path: ENC[AES256_GCM,data:HkMoEFeaWf335UUGx9MMycQuriEr8BYa/Sg1BF93IIpZeQNGLPKmkknkCieEzD+4+f9d5ule,iv:yHqxHYmhXEtdYO9PB58HR4J4S21Czi7u8B/CBjA3Avg=,tag:bohOzEQzpuY6JgclUPMkig==,type:str]
                    type: ENC[AES256_GCM,data:jNZX4ZPM8Rg6,iv:Ty9mw5PsrD2Y/1Is5IvgYnVUDNlutdQEfjMlCKs6SxA=,tag:YElTrSCBNaQKBgdxA5a7hA==,type:str]
sops:
    lastmodified: "2026-05-13T18:32:09Z"
    mac: ENC[AES256_GCM,data:ZuOFgrTMxx+1CcRqzVSXUhFAhkbJjPGVEnApQAgZNXhudMkNDCxKUJN1S7UlKeXX5MEmJeyu566BY+LYilUXYLYz2kran5KEpmT1GG09syAvxUw8dO3VUgqVfYWNyeaSWJUQQLE7Cfrpb+0AQwMcMea64a3JYPMmAVSuGkEdMGg=,iv:NiLR8p3pO626dv3ucriPr4Q9Yj9MNDIg4hUo1MngURI=,tag:h4gClthQ4YpEcBP2oDJSjA==,type:str]
    pgp:
        - created_at: "2026-05-13T18:32:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC4LUCsV/V+wSAQdAOSNPwDj7YZvk9PqhToAtUDAdBicl2XsBcvhkRPqTSX8w
            QpPKc33khztGrHAk03FfnlTzlds9xkJH5pM+EyVqj4N7C/j01GBlyMVaEqAkEYLW
            0l4B+Ce79HkE52mQHfrONe5700pYcl7cscba8GsTgTI6ShGwvPEgSiaSGyUO6b+t
            gmB8qD051ccC0f/DDzZw5RwH3BEZOIA7to4K3K8cPWgHC8pFbD/Pv801nQ7oJxPJ
            =wrXo
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2026-05-13T18:32:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdAo+Ut2BoICDE5FE0V2Kmd76DSvW5B+7VoGzdn5bGWCDww
            TdZocJ9SMJ01ftjiXvpPTtbh3B/SbCXvZ5Rgn04l7mhLw+k5EnW977bVpmL4YQ79
            0l4BC9vXS+A5Dczzx9RUICD7EbpM0LumYeov3Fnq3Exi5mC9zfGWZp8ao2UyhpRw
            0tHCcDQ85psdQz9WDZaEyx/g4wORnpx0nKUR8o1ZnS1+moT+jLtV6XM+HOAX02bs
            =E5FB
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    unencrypted_suffix: _unencrypted
    version: 3.12.2
