apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 10m
  releaseName: eg
  chartRef:
    kind: OCIRepository
    name: gateway-helm
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    config:
      envoyGateway:
        gateway:
          controllerName: gateway.envoyproxy.io/gatewayclass-controller
        extensionApis:
          enableBackend: true
