apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
  namespace: flux-system
spec:
  dependsOn:
  - name: immich-db
  - name: immich-storage
  - name: envoy-proxy
  interval: 10m
  path: ./flux/apps/immich
  prune: false
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
