apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
        - name: caddy
          image: mirror.gcr.io/caddy@sha256:cb9d71ad83182011b79355cd57692686374bd78d6fe327efe0ff8507da03ab13
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
            - name: config
              mountPath: /srv/index.html
              subPath: index.html
          resources:
            requests:
              cpu: "0"
              memory: "0Mi"
            limits:
              memory: "300Mi"
              cpu: "300m"
      volumes:
        - name: config
          configMap:
            name: caddy-config
