apiVersion: v1
kind: Secret
metadata:
    name: umami-db-credentials
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:qS+IAos=,iv:ajJ0ma+LX4qFH8OZLtAvD3LPjUY66E+fK3UNfwKZP2Q=,tag:6aPZWerKlzBXKCvIe/bx8Q==,type:str]
    password: ENC[AES256_GCM,data:9Bu5F7prPbQTHCzCriQ1ZCC4dmhHcEPyUCIcPnQnSHJsK97bOzTyzQ==,iv:fhPuu+eh5jhf0QBFif2IsWRKoxNhyZFtp+RIG1hKI3o=,tag:STsol1lJVvWnhXSxVskWOw==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-27T16:49:16Z"
    mac: ENC[AES256_GCM,data:ARNDFB2NjQMuJr0v8p0BjHf5q3DuaYaihDOkiH7gZfHKx5dyAoyibPPVdMpw51RJj9YaxoG+LwZbisYH+xPirJeP1+6C/u6Tvhnxz5x4MyiHAKI7wDwLcUCQLN8bGC392pNv7k35M3lL4vhcHtrA1mpk6p2BpLvZTLusLRD24qQ=,iv:muao3wnmJhqE7RzDKLyZsw7Dxzs4rzIuwzmbKcOSgJ8=,tag:q+6pVJWGud0sNT7N/zKGtA==,type:str]
    pgp:
        - created_at: "2026-07-27T16:49:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC4LUCsV/V+wSAQdAXWvgek9l2XuAzhw/LMHqJiiS5Ydlpvo9IV4JbRbZlXMw
            AL6hv7exEthYPbnMvar2eneHM4y++wP+sdLG5TIZnOKLmVEdRllCTVgJjVSOY+OS
            0l4BRintuHPHGvDHZmJbIDSp31ZHxA7KXeP7tDopGz9CzJ5L1w6lq0kWB5rmkZ9T
            auLP4ju2QsNUQQuhWMaJVU0VZOER3X3jlgV4xRRJ4Zc5ihh2p7QvMdPD2gyQEJNA
            =Bp29
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2026-07-27T16:49:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdAxWPNFq6ds4KmC38ykWXwSkoj39zG3mmIcWCqCDdpOyww
            Ye/Wbbko3KG837w2dEpzsVS0JLyau8596wDtuwiX6tXAR4RZ42sIJAnYbph10Spk
            0l4B3ZOrXuna17frUdEPYT43+SG56MHJqrDrICQ1SKisfCWh1zUoQdWxoQvN6fSA
            +aWNM5F37Fh5eHiE5o5FPs89l4MIaYQAGAWNupRAa75CYrZO52wvm04/PpQAk7jO
            =UXTU
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    version: 3.13.1
