apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: asteria-node
  labels:
    app: asteria-node
spec:
  selector:
    matchLabels:
      app: asteria-node
  template:
    metadata:
      labels:
        app: asteria-node
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: asteria-node
        image: mirror.gcr.io/ubuntu:latest@sha256:186072bba1b2f436cbb91ef2567abca677337cfc786c86e107d25b7072feef0c
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host
          name: host
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
      volumes:
      - name: host
        hostPath:
          path: /