apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden-db
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  dependsOn:
  - name: external-secrets
  - name: postgres
  interval: 10m
  path: ./flux/platform/postgres/applications/vaultwarden
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
