apiVersion: v1
kind: Secret
metadata:
    name: jellystat-db-credentials
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:iGFofQGvfgxl,iv:smqy0kJN8TKpBn5miysObHT3nRnAUKhc8hOvsXlWOEo=,tag:fNHInm1n4tno/QgY7B5AvQ==,type:str]
    password: ENC[AES256_GCM,data:iVr/0p68bv4Wl11Tb7iEEPd9Imv6VPjgF3ZedX2fIRHEqcNPC7t2xQ==,iv:6FtjwzfcYdM9QeWmvNLAnhbFXo3HcWeJUcj+tfIuseg=,tag:TbY/39g1+/TnyQwHh4i3IQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-09-19T08:31:28Z"
    mac: ENC[AES256_GCM,data:u4D6zb+SDFBDZipbIRdNvZtRPGfAf8J5lmtNFK8uNXwngcbEtfUWXruP22p5vqEU2r7R/UAhmw2O8FxfJt2DdFt5NldAP/xB631cwq39X7UV6DvW0Tk2VQ2nJNRUArmOy96xOUoH82cUAYVzZMO+GJfM85D5At8X1WNQB9SWBgI=,iv:EwPNRNvQ+PLBROdbLgZEaB57Pg1cewxLjzVzObLhUdM=,tag:cggtrDVBPR9rZFZDVfrP/g==,type:str]
    pgp:
        - created_at: "2026-09-19T08:31:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D7/45ZmvAFBwSAQdAtbNOXwF0ss6IgcBACGWxMsL6nj83MIUoEgFpAhAGLFIw
            xJyo6XkQdErfPdWeiDoOyi7blBSbQUOpAXhtqLlT0ACCg9rVHtav6lkf9IWIZuOr
            0l4BXN1pfhnlUNVaZ9wqJdVUnBHkKa2+vMiWLJwiSvvKmnoQo9aiHcBPdZ8xXpUZ
            Fs2fJuWwzUlpQg54lXa4z4n0/Z697BOABL41WcsQfnSMyBIZLyEz4N9azuEkEO7C
            =4yB7
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2026-09-19T08:31:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdAYmEwwDyKPSHckvkxZTC30pZSCqXntpz0o3SjjI/K9Hgw
            WG4Kj40Cd1cNejX2AQP5nEd7Pvd/36mCNmE+ZwQ9x/ZfG52mP00P0MbdDgjPHALO
            0l4B6tgGM10ZBdiJ6hOCbTWDqdG6J7BWbCCdt7bMlIADQcNJ9MLOSC15+fA0uLZa
            DZxw+7+Wi2f430UrQ3LG9r+GghNBZk0PpIyEjliO1NcNnU/EYxDNTbbRMzL6Xvfg
            =JPt7
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    version: 3.13.1
