apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: policy-metrics-server
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: metrics-server
  egress:
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kube-system
        k8s-app: coredns
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
      - port: "53"
        protocol: TCP
  - toEntities:
    - host
  - toEntities:
    - kube-apiserver
