apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-proxy
  namespace: flux-system
spec:
  dependsOn:
  - name: envoy-gateway
  interval: 10m
  path: ./flux/platform/envoy-proxy
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
