apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: vaultwarden-db
  namespace: postgres
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
  - name: vaultwarden
    kind: SecretStore
  selector:
    secret:
      name: vaultwarden-db-credentials
  template:
    engineVersion: v2
    data:
      uri: postgresql://{{ .username | urlquery }}:{{ .password | urlquery }}@postgres-rw.postgres.svc.cluster.local:5432/vaultwarden
  data:
  - match:
      secretKey: uri
      remoteRef:
        remoteKey: vaultwarden-db
        property: DATABASE_URL
