apiVersion: v1
kind: Secret
metadata:
    name: umami-secrets
type: Opaque
stringData:
    APP_SECRET: ENC[AES256_GCM,data:tFa4jeZ1PcIIC5nSLuy2IhORX054JxWxV9VaemnazBk=,iv:WqmCvZQ4JY9sEs33UACpfH03ndO045DBw9RxKwYAXdI=,tag:r5gUui7hU22tgPoDPFOBHQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:1B5iHrZRtU/RGNFQAabuIo2eP3yZ+N9mbEdhpGeuTeiiiy9vh813Zrgh3ghcd9Nd/UyZzXOT4TYe6rRi1bNIRlKTUcnDC+2WPily0prFmdOuiu3HYNo=,iv:zxAHsBzmqkWwiwn0DiSQpDWhsP9uGtkGwZzEeeofCjI=,tag:QagJ8iumW0J1XFWiAqJ1oA==,type:str]
sops:
    lastmodified: "2026-05-09T16:46:58Z"
    mac: ENC[AES256_GCM,data:MtxgWqUlKC5aKJAemu4lVeJvDrf36Srxd2Tc79NxBlZgzqQR7E7N1t7eQSIou0HRuSClnSwrnNNjSI262BmWxcoeXoyf3h4Q8zBS/Iu1VwuXokn2PBPsPJKmuOyN0AZVTwz1zCuypxfss/vc8nLRZuauepPbcWsPxXr6VtiSio0=,iv:lOo+bsP0biV/26s4xhJEQp0UIpPqgioQZHJoqGYbCm0=,tag:hCKYLTavWDMSXxtOHILKeA==,type:str]
    pgp:
        - created_at: "2026-05-09T16:46:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC4LUCsV/V+wSAQdADdEjmmrq+zFmLxZ71HN8qcA0pcuO25zh+2fX6Q6evEkw
            NisHQpQfa4CIOj+wCVcQE564yn1TbyFGu2WhttG4HL8S2LmntbY0uBxDknKOsJFq
            0lwB1snAAd8iGLXvqIWSoMSgIHpM2s5PwkxGSgwF6Z8JzQNRS+Sw/EYRDUU0vBL7
            Qu1vxSWkFR+NeGnn2/hkE+DSMG0AZdpf9XaKCZ9uLgsUy9Dfes6Bmni8+p6pwg==
            =/Vx+
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2026-05-09T16:46:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdAA9acfhRbu0Kws/U/IrO8hHc9wMP0An6wzNOrn17yo1Mw
            aGOBE6mIDQmPpkM6o4rPz6bX842JGZeMygjaVjkodUIbiS1Av8STcgBsKbpz29ze
            0lwB8Hm1y5O8ew4GZ3/e62bOdtIawri+GzuOWCYjIhieV4fuM7aVFBFvJp5cWSf9
            /4XFv+7jMs35PzSPVDMdyCyqyWpQdaY6DMMwhfj7bC0iiaBXJCZhCyfcgcLqkQ==
            =ny2F
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    encrypted_regex: ^(data|stringData|secrets)$
    version: 3.12.2
