apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: infomaniak-webhook
spec:
  endpointSelector:
    matchLabels:
      app: infomaniak-webhook
  ingress:
  - fromEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: cert-manager
        app: cert-manager
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
  egress:
  - toEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: "6443"
        protocol: TCP
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kube-system
        k8s-app: coredns
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
      - port: "53"
        protocol: TCP
  - toFQDNs:
    - matchName: api.infomaniak.com
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
