apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radar
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - radar
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: radar
                port:
                  number: 9280
