apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-ext-auth-from-apps
spec:
  from:
    - group: gateway.kgateway.dev
      kind: TrafficPolicy
      namespace: servarr
    - group: gateway.kgateway.dev
      kind: TrafficPolicy
      namespace: syncthing
    - group: gateway.kgateway.dev
      kind: TrafficPolicy
      namespace: ytdlp
  to:
    - group: gateway.kgateway.dev
      kind: GatewayExtension
      name: authentik-ext-auth
