apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirlingpdf
  labels:
    app: stirlingpdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stirlingpdf
  template:
    metadata:
      labels:
        app: stirlingpdf
    spec:
      containers:
      - name: stirlingpdf
        image: ghcr.io/stirling-tools/stirling-pdf:2.14.3-ultra-lite@sha256:8eb382b98aad9b69180c8f7398a06f189e4b5c3128ac3c204b4517de708df325
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 8080
        env:
        - name: DOCKER_ENABLE_SECURITY
          value: "true"
        resources:
          requests:
            cpu: 0m
            memory: 0Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
