apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: scrutiny-config
stringData:
    scrutiny.yaml: ENC[AES256_GCM,data:AErxK/eDKjNOrvB7k0ONDMLpX6BFhCRWjr1llVXH881v5HYmsHvTx6qEAy3R08R+WP00q2HH+KUTsf6DR9/gQ9AhsnFLxS7rXAJ9Wa+/FRG1FfkM60YOQkv6hsewUtRtdSj5az/AQK2ho885eiKdqBYuKmWp23Rs6quwzDRSg/JXiLoM+2tt7fhp2fxhKedLYAQKMdF6sAA32IDXF+4qL4rJUMe7vPQk8X5nyGjOllSmpTjadEokb6T9AU3sjEqjk/5Jojz7PasVsWdqC/7kODwgq/25S5iQFgCFxyHWhvE4I6amYYyXaYDgfeEz6WXoWtaS8BlyQafRJKG09x+8qab7nACa2bwV3Qjwuv5e/OgAUi2aFWIMS2SynQLDLBUYJNRCb58f6ffGxSIWjidHxNCajy4/7R8YCjV6bdmk5sDKKwhwn2RtyS11Lur0GvFXbwBSUw8BQpMdECoTmedkTZWQPtaN5oweIAcbOwwLnKGWwJ9LOxKZJ1REVKq3rV6YuTbvtfKfo1yUFKndIDq5jJiITutd6EMoXA==,iv:5do1XnfO68b/wm0iQZ1BDnhMyIYKkx03BtHrASom13Y=,tag:hD3YB4or67gWscSz1cnNMA==,type:str]
    collector.yaml: ENC[AES256_GCM,data:Ay60+vNL141rJmKUgIUwi6c0L6R69o2K5Xt4OmJPgJvvH8RXQSnVIZRX0xpI+wMnBsUdePa+mlvDjWHl8NOvTiO4KJSyDn+qH3Une2zxp2OTGXzBBcFgKHnd76BoFIvZIA1+qAF+TE9/3Qg/GmkNfGAYQQ==,iv:yJyhFC+N8UcpwH9K6T4A/9JAf0AnRdXKRcWq/GqHyLY=,tag:TZeYqO43WWkuuay0NFdXRg==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-30T15:46:37Z"
    mac: ENC[AES256_GCM,data:Rj8zzpdJffGvjNbDiPH2IS7106JAZ+j17DeYtncJ5vL1vkxMnxCiQYy45FXlNnXCXdgCXuFa/Jat6MXq1z9u19bellgR1Tu6bUoMCNJJL88stxdFGQruOaPYk63KDde3DWteXu4FqMsiSQPPmO917wEH8FDOskvKw4a6ARH5XX8=,iv:6IodGWB88jEdwOb/mvvdCJd1iqTKxtrVVbAW2PvNWAA=,tag:E6a/9XcypSt696J/Qb3PLw==,type:str]
    pgp:
        - created_at: "2026-07-30T15:46:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC4LUCsV/V+wSAQdAfoD1nh6l0YJsBFqzV5y5J5VQtICJbWUQMfiFoqcD0mEw
            sljFBKh9SmxBZfeBu/ZPGOsKoiOzX6ET/zL+lFmpX4mHZTo+kvIlAJ4IxmWjuCVM
            0l4B4qdu0eQygvs83Fga4BcLIdm1s+XJLYg8BD2kACtKDY6CmlzvZcW/mIkkNH+1
            I9sMkQqL0qP7KgKZCcRcIMapWm+0v6eOmn08svPN+JUo6IhaE/VetfSbq3ES1vX0
            =0QWi
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2026-07-30T15:46:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdASRQtVFbaAfUPt87TW+yb9DIEu3XMStL8zwoKMVaOl3cw
            Qt1RvoUv6IwCRsWcwhkHPDVmk0TRf/07z18A8LmJTIFwosYryw7WsTEoUq+MXcjs
            0l4BzRGjABLdEAioUhKiJpLfgPL33bew6EFF3tY3r53TtfE4V+vx01aIR8AOoWEq
            eHgvo/VGpGYJh/rwCBcc1KRBDXD+Gcysg9DttCgepVZOM21W6+6BU8YZA0BzAggA
            =7EVh
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    version: 3.13.1
