apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: woodpecker
  namespace: postgres
spec:
  cluster:
    name: postgres
  name: woodpecker
  login: true
  passwordSecret:
    name: woodpecker-db-credentials
