apiVersion: apps/v1
kind: Deployment
metadata:
  name: satisfactory
  namespace: satisfactory
  labels:
    app: satisfactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satisfactory
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: satisfactory
    spec:
      nodeSelector:
        location: home1
      tolerations:
        - key: "PrivateNode"
          operator: "Equal"
          value: "home1"
      containers:
        - name: satisfactory
          image: mirror.gcr.io/wolveix/satisfactory-server:latest@sha256:e103700ae6ae4c50f19dac80eadb2a805c5b885e179ae2a40850e967bf189efd
          imagePullPolicy: Always
          ports:
            - containerPort: 7777
              hostPort: 7777
              protocol: UDP
            - containerPort: 7777
              hostPort: 7777
              protocol: TCP
            - containerPort: 8888
              hostPort: 8888
              protocol: TCP
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          env:
            - name: MAXPLAYERS
              value: "6"
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: ROOTLESS
              value: "false"
            - name: STEAMBETA
              value: "false"
          volumeMounts:
            - mountPath: /config
              name: config
          resources:
            requests:
              cpu: 0m
              memory: 0Mi
            limits:
              cpu: 3
              memory: 12Gi
        - name: frmcompanion
          image: featheredtoast/ficsit-remote-monitoring-companion@sha256:6c003115f5b748687cdff1dea963d956a005fee6239265e357ea8b14c7bfb18b
          env:
            - name: FRM_HOST
              value: "127.0.0.1"
            - name: FRM_PORT
              value: "8080"
          ports:
            - containerPort: 9000
              name: http
              hostPort: 9000
              protocol: TCP
        - name: frmcache
          image: featheredtoast/ficsit-remote-monitoring-cache@sha256:54a5c77cc05738619d41372e7c86567843c94f65ed56495d1aef1ae60ab731a1
          env:
            - name: FRM_HOST
              value: "127.0.0.1"
            - name: FRM_PORT
              value: "8080"
            - name: PG_HOST
              value: postgres.postgresql.svc
            - name: PG_PORT
              value: "5432"
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: satisfactory-credentials
                  key: password
            - name: PG_USER
              value: satisfactory
            - name: PG_DB
              value: satisfactory
      volumes:
        - name: config
          hostPath:
            path: /media/disk/satisfactory
            type: Directory
