apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: satisfactory
  namespace: satisfactory
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: http
    scheme: http
    scrapeTimeout: 10s
  selector:
    matchLabels:
      app: satisfactory
