apiVersion: v1
kind: Secret
metadata:
    name: uctf-db-credentials
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:AGB4eA==,iv:NfYEmaZI7Gn63plzWWpWDt/Py41UkQi4S0OQlFrWlXM=,tag:KGuCXbamG7Cpho2mD5rMpA==,type:str]
    password: ENC[AES256_GCM,data:IIAH72OcQaw60PWliBiHeWU3n5k87Amgwei/SeHoQ+M=,iv:Dmp/1W/x2jehzW0xJ69H/9DCUNyU57/OSacHpbb+KT0=,tag:7OY+aNjAZHv9JYeD2cArLQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-29T10:45:46Z"
    mac: ENC[AES256_GCM,data:nO/0MnFZe/Sn4nd9N7lVxPZauJyyZiv/AtNCTIPX6dydDJU79Ezp9rQ5s6o5tIx/wEEEA4Et0rNLN2d+CLgHPkODnk3VCvpmLEQQ82zuC8kXZVVqWbl0jl/2TKEnsUQhveNA0EMwEjO+CpP2o5822XZoLZfWjMYbi3KZLYgRghs=,iv:jceF9fArOHr5aOXFG/adrXFmzu72IPNIIIhVcaGOkbE=,tag:q7g4Sbl8hwaddYUpKbzuMA==,type:str]
    pgp:
        - created_at: "2026-07-29T10:45:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC4LUCsV/V+wSAQdAF4AlAd0CrE9Ex+4uLjDxqpUMUHaBR1tljCC2FA8hMj4w
            1KOs0Dw6ouHy4Guzbb+7MdfWNv1aVq6vsSuG0HQ3tzDi/TU5KYL0cnABqG7NUoSA
            0lwBEwAJ51tBe71H1nBScxkfdXoTX+kx6idCUtjqD68qslGYUTWDyN2BLaFhhE2N
            u6Jk9XlOlO56gm/stqLbncsMH20x0KW8FIHIoFJb1jL0AWtVI+KkJnWxGaytRg==
            =1H35
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2026-07-29T10:45:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdAO0voU8GDtBXtnwh8WK38y7pW6IDtyHsJ+Y2TcC0UAhkw
            V/Tv2yKDCqK+JZObnxXLn++nMlzYBcDH0TpcGvYErKnHvfsn8e2sAgxNc65uuu5h
            0lwBVJqI7Om9WJSZ4LHsPNKJfkxiHNMu9gojMBsdkrAKu6y8BrWCW8BjqzuNER8Y
            KnnjA+T4c6WdJnNve0xae5sF92jlaDRtRwCFITSACHz9LMZU7gmIcMYb3t3Gtg==
            =zHWD
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: safran-db-credentials
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:BO8rwe5m,iv:hLQm1KeUtIqGtWs9QpncmF9uLpx0WJDWH2G0AGnuamk=,tag:WcK06sfNXi7Di0tcgj3ywQ==,type:str]
    password: ENC[AES256_GCM,data:9fpUZ2o6MRaZUBVFd86xkvkgn4uZ0HU5hyhmHXiphkE=,iv:5BPbBTlRjVBkYwBKIxTVz9B9zYXWbqStdEHa7N9YDns=,tag:YfPQ/FXl1WvaL3HBX+9Uxw==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-29T10:45:46Z"
    mac: ENC[AES256_GCM,data:nO/0MnFZe/Sn4nd9N7lVxPZauJyyZiv/AtNCTIPX6dydDJU79Ezp9rQ5s6o5tIx/wEEEA4Et0rNLN2d+CLgHPkODnk3VCvpmLEQQ82zuC8kXZVVqWbl0jl/2TKEnsUQhveNA0EMwEjO+CpP2o5822XZoLZfWjMYbi3KZLYgRghs=,iv:jceF9fArOHr5aOXFG/adrXFmzu72IPNIIIhVcaGOkbE=,tag:q7g4Sbl8hwaddYUpKbzuMA==,type:str]
    pgp:
        - created_at: "2026-07-29T10:45:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC4LUCsV/V+wSAQdAF4AlAd0CrE9Ex+4uLjDxqpUMUHaBR1tljCC2FA8hMj4w
            1KOs0Dw6ouHy4Guzbb+7MdfWNv1aVq6vsSuG0HQ3tzDi/TU5KYL0cnABqG7NUoSA
            0lwBEwAJ51tBe71H1nBScxkfdXoTX+kx6idCUtjqD68qslGYUTWDyN2BLaFhhE2N
            u6Jk9XlOlO56gm/stqLbncsMH20x0KW8FIHIoFJb1jL0AWtVI+KkJnWxGaytRg==
            =1H35
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2026-07-29T10:45:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdAO0voU8GDtBXtnwh8WK38y7pW6IDtyHsJ+Y2TcC0UAhkw
            V/Tv2yKDCqK+JZObnxXLn++nMlzYBcDH0TpcGvYErKnHvfsn8e2sAgxNc65uuu5h
            0lwBVJqI7Om9WJSZ4LHsPNKJfkxiHNMu9gojMBsdkrAKu6y8BrWCW8BjqzuNER8Y
            KnnjA+T4c6WdJnNve0xae5sF92jlaDRtRwCFITSACHz9LMZU7gmIcMYb3t3Gtg==
            =zHWD
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    version: 3.13.1
