apiVersion: apps/v1
kind: Deployment
metadata:
  name: yt-dlp-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yt-dlp-webui
  template:
    metadata:
      labels:
        app: yt-dlp-webui
    spec:
      tolerations:
      - key: "PrivateNode"
        operator: "Equal"
        value: "home1"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: location
                operator: In
                values:
                - home1
      containers:
      - name: yt-dlp-webui
        image: ghcr.io/marcopiovanello/yt-dlp-web-ui@sha256:2e88e452846b35a3ef4e3ece6ed0a3bcf747f3fa330ee397a72d9331d26cfade
        ports:
        - containerPort: 3033
