apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stalwart

resources:
- namespace.yaml
- recovery-admin-sops.yaml
- configmap.yaml
- pvc.yaml
- certificate.yaml
- deployment.yaml
- service.yaml
- route.yaml
- listenersets.yaml
- tcp-routes.yaml
- tls-routes.yaml
- backend-traffic-policy.yaml
- network-policy.yaml
- zones/
