apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:jzvpRNVK5quP85kiX3OMkxfCLArspLgdb9QDWcQa7yuj4YkHXGmKHdGQxq/l609TQhzd80QPqR7Hm1/gDf3n0g==,iv:PXtUCnpERE17VmorHDl4QpzGaob60+w8K2rn6Ev57e4=,tag:MN4oMZlybAHMHN9sOV+ZrQ==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:U6GISUlHjnhdhMl9oTxtjvoofK5+HOXoRb+/9B6fijUXqQBXU72xc2LRQm1uyi2BE+vQ9mTPVDe7Y6UEkUNZ6A==,iv:WkWZvMtPeAa/D6ob0Z5q3adsc/2N5tr0Objzy3jwTmc=,tag:xPl15CAisvBtrU+jpdeVbA==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:JHo3otlVdc7Ekyz3jcjvg6uIxhk1X7QLMGBCGUj21RAMHVjw7UagcQE3KXVinYuHhu59g/Tn9tsXDHG2qBpVu14xw3+072FD0JYSgvqmtwxcwBQj//ybhWBjXMxnWITbcK5W8/IH5CpuEKrUhDl6yp1mg6twd3z9R+Q2lcF72DJ4eHPvRUMepBBwBpkps43v6V4d4jnZSuMUace4xygpOObhYXZ8HxBbwe1B2JnXNUx1aGULtzM5Wk8YSMRV26W5j5ProN5kyOE7x2cK7gadA/KQA44rD3RXimXZVWuAspytVmATd1i8C355RwW8/cOf+uLtHOGi+IxqmDZxTnfSPBsv/zX/yaDvNKwTazOaPxLJTpTb7bizSmX0u3HmhAMLcIMS3MgJu6/yHE1oyVBTMahYCRwiKDK06c1KWRI+pJbsqbu/zBADHrfpXj1dx/QYxmXyf9VB/KrB6DvZ1KMfyaVTKWQoBm0PhqYr4HzVoCBinxqS57nvvg5OaVvUXoc3fMPPVMh2hEVUbngiGoLljklhT7WUGkFZdvDpIZLkZUzeXCyt7JWM5/+jqx1TqOjhQ+tIrMHTjHSTTtwBht4rdELvWrmzj7I1YZZFf9KnwB/ZiamiioRrlnmlCOnLZN+f9THETvczUF6eoAP5x78NjrfKge6z6HdNMFS1Fth9JojToejAILfzmTKtND0rMlDEL3KtkMUtCp0a4rgX/sm2n9vrXvnH6b605MKbR5fE2Nl2MktdvLsbpBA0Oj5jq+QVCJrcx/wY727MHJqmJKgikfUDP8g1akL3ZJrzHS/4m5eD,iv:DU2UV3wFTuC4tIhxcV2AjpXo+tgOdR8yhzxt7dEJEuM=,tag:E+0EChQHNGwRzP3gP5SU5g==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-06-08T19:06:06Z"
    mac: ENC[AES256_GCM,data:egR01IfIFk1pQh+MK42+yBWVx7XfNLHgyctaV7AFFk6uDD8Vk8bX5j+vofKgK1U5Rw1Iv3wXlvaXRXG1UFc3w5JHfwK6SwE/tuRL53+pkKIcaEYc4yyf1ZzUJLGeHlZRycOZceDSubwn4w9Dl9wcY6xlGf1BAha+1TMjhDwevSg=,iv:+YVZD4ylQIpKaYdncZ/OLBGYQi9MjnEYt5j4gGIJ9FI=,tag:gvRjs7kzYKlBNbji/wpuOA==,type:str]
    pgp:
        - created_at: "2026-06-08T19:06:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC4LUCsV/V+wSAQdAcWyjqIsvK4BJtYk/6dmNIAaOSjYwY8bLPKG68vuQHSUw
            oFVr7MFKvkAcy2VIXCNszwvJcu/MF+FWnNLyEhGnHr4TznXPL4gqhj85WKKFCvHs
            0l4B65V29hdfn+EzH6pNkgX/Ed8prQ9Xxow1mfTJHh2hCeMU5l2VyiRYxSS8RgWI
            ufjoTKqFanv1oOhqiJFQNBpgAqMdfdl8JcqqDI5X6JHqAiV7KZP2Fya4rHi4rLmb
            =ffk0
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2026-06-08T19:06:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdA2agdVok1NjvEGJttIzY9T1XERzmVRSdnYWqz7HwDrwUw
            zIBkLfZwTBxIL8uCwi00CrQtMEmmXZA2z29NefO+F8avqf7G3DqoGbrRfcfo9RnB
            0l4BXZv1WnQVGdHTnFcWM0T7PtT3jTX5mEbHPUjKABPjdev60RHa7jWdT4exEfLG
            pPS4/xObJj907mXQtoNamf12BWAmVLoKfqEnYnhCoZg+2f8xfSALqFhX+bTlU8AM
            =w/Wb
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    version: 3.13.1
