apiVersion: v1
kind: Secret
metadata:
    name: frigate-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:3tZO07F8DXEXrtwbwHxXU3fqu4ISBR8bMm1DzVx4Q5H2Yapsdt4L027hhcQtdDzbLZOStFozv5zaNHc8yE7vCLDt+a5MehwawZ4=,iv:uK7A/XU38TlAoP+LMhqbpQ8TC/tikKMUwSbg5V9eERM=,tag:4qOELfzojn2P+5aw/tbjeA==,type:comment]
    #ENC[AES256_GCM,data:uIUgvOHzGE83GbIfqjrc5jZNbt69btMkVRQX+P7Kou6DknVxANxX5MqjpJJyZW2xmpbRqY7p0pgsEpHFk5ycSAr6,iv:FsgssKj9oW4CEgAC9b+jzhjhr984tIk8uOsV/262xlU=,tag:gLYgXnYnpyLyxia+RRZXBA==,type:comment]
    mqtt-password: ENC[AES256_GCM,data:c7BfpLQHwwnt4An2wGJ9RpFu5DY893CXo/PXqyjjXsoi48JkMfuq1W7ggkWE9yOv6rkRtY9cQJ3uwMRG0XCWGA==,iv:OZYCdXboJ4YKEqbDnnQsz0oy20G+wJIIbPalTNzesZE=,tag:5gQPXeQA2/WMvo7AV3Zdng==,type:str]
    #ENC[AES256_GCM,data:Jmpm9+dXKw1osYmXH27K/KmAm+RRTuw9jjxisjUhYCphiP3W6oBp7NHZC0qQmkxirLOFMXtsRg==,iv:jORNMdMT25gH15roB5RfbN8hSvjiB7bGLJus0I833VY=,tag:8P0+oE0UUQYQH7CG2BJFkA==,type:comment]
    rtsp-user: ENC[AES256_GCM,data:G+VfturH,iv:2Rcd0pGnIH/NfXofD5SbGJKkP7lCeC4zTvY89XJmhoQ=,tag:w5fqMyLOcAOmpirJQ5t1CA==,type:str]
    rtsp-password: ENC[AES256_GCM,data:vzIHFl6vDwa/E4FN9IiTAmlDEA==,iv:+BIbYJzWnQe1Cz4JY/iM1wZ4Ac9H2zwsQ0+D6GATUmc=,tag:F2d9EAIsK4G+BD4RbypzyQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-08-07T17:45:06Z"
    mac: ENC[AES256_GCM,data:28ztTCFOgOgXh6KqafrvmK3na62akt27683OtaGArE8zL7WdGLzMbVFEa3XWQwDbx8DxDtC9dOXopeJec6t1F15XTG54N8cxe6oj0uO/qJjMZ2kdTnPEUr3opf1Um4LeWHsDHWWpK8hOsh1iSCwOoqNevqH/959TlilXtzFGlxw=,iv:u1r81ZnddZdvLSlq07Y7kcnGoEwjflVfwfNCWnPeC6Q=,tag:EOU9afVhDEQUWaUrq74d1A==,type:str]
    pgp:
        - created_at: "2026-08-07T17:45:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC4LUCsV/V+wSAQdApn9Hr1XsPDP6hFdPok61Xtgwu1F8Dy2pEwaWVk2V2wQw
            R37P939NJf0VSQIqNeLM5XvRO3JHdFFKC/Y+6yU6T50c6PmbsTrczGr35KnwV7BJ
            0l4BXUdMQkoJr9FR6xyLPV5qy9I4d4xNpyoZYUw47U+8ABj+6xja/QrHagAfXAX+
            OE9jx8k4gErwHKQvGd4ADWu0GGIQnr1E2apx3MJcEeGKlO05clRywqCHwJ7BtJaI
            =W+VD
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2026-08-07T17:45:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdAHHFz42pj94iPf8Yf7cl509S9cl0XwLlVE71YCnWWfGAw
            N0APUW52N+9U7oASnEkmHZl0kg+keZijc8Hdvu5mlRjLAUCjqmC0fWuj2amKi3ZP
            0l4BVs0tRUcEHbPgVcAVQ5EkAWHZIXeWQnJmKJrO6+R9vw4aa0NqqRsVCTChhYKv
            +JtL+wv9XVFchKvHWdxX2UV7h1miN/Tovb7Cm0nRmLzj499wmZRPZL1Kw6Dpv5JN
            =VkQ4
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    version: 3.13.1
