apiVersion: v1
kind: Secret
metadata:
    name: frigate-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:iPY5PiTcWoJ9FJSwrqzSZrDCBuGaPB9k23b0qFziAOUQOyJ51CQI+1C0EOmEwrzxbj2P+TS9wrdgJ+Xwf+DN8qwPUERYaCFwQvY=,iv:YFTQIdB1//sUaIgLXDokFksdF69FS4eiulEbsra1Ea0=,tag:3BTGa2eH6ySeD+ag2DWPiw==,type:comment]
    #ENC[AES256_GCM,data:uGYzpziEu44WlcV/wHhiXcJ8DWmIUQGBUrVlowIpCk7q2A8q01NzvOoB/bOF8T4HQXiIIH323INAAGTKt8oWinE9,iv:gu5LVNLT/y77k9qtzMea1Fkn9DZ39WsMBFHMcZPZKGk=,tag:QDwPBJGvQxtSvWOmXI+9xw==,type:comment]
    mqtt-password: ENC[AES256_GCM,data:H07NFpfoCcGsucEl6n7qX7uHbCV9Sj8fURumtihNmA9QLW0gxu43PG1TjBCrEN23mWuRLBvuzESYQfFFx16Qrg==,iv:6b7qJOeMbA8ARbu2ZdMpwBpy+46ix1V2uMgdDyFgcGQ=,tag:czmh96fzIyUJWCd18/49xw==,type:str]
    #ENC[AES256_GCM,data:yE1NgVixNa9pfAFJEADvKGDjKigmqioAD0DGl/P/bC3wvMJJalvlscRjLArh4zTd+la41cpjxg==,iv:iNokyec6f1eHHDd1+I6BgJq9CybG+BlM5F5dkwerH7E=,tag:IdyjWRncr8LbGrr7AA/DKg==,type:comment]
    rtsp-user: ENC[AES256_GCM,data:weVrWVup,iv:SZWZXogqJaoAnG4/6Qu7j42LI+wTQhes7Vz4rHKJZ5s=,tag:pftXUyt9UQyYpsBTnTbDvw==,type:str]
    rtsp-password: ENC[AES256_GCM,data:3IKlILxqy2gHVugYT2ibV5HFrA==,iv:AyfdtYX2yQU6kCStJThRugbNpXp5ubGZFm98sVwEp4Q=,tag:yunIu6BLSVPFuaTQjrhHig==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-08-07T18:22:38Z"
    mac: ENC[AES256_GCM,data:PIqxSYLDx1hcAZTyqGwE5fOVcVC2xEhYfyUNgH+u8LFqVaY714WD5344ybHeyfgjBzl8cfqwY+1hhZJVXrnnXnjVV+AOvVjNILUu0kQP2hLzXXmVhwDjQo02QtglgJKBqMmqN+WQqNlBE/cqRqwvuHRa1q6eOkw1CL9mJPhauyQ=,iv:VLSpmr50YqAUnGRrYv3H6UlDwU4cdusj3x/MV1pskCM=,tag:gd1eaZfCeLEadsPrU+RggQ==,type:str]
    pgp:
        - created_at: "2026-08-07T18:22:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC4LUCsV/V+wSAQdAkfY3GlLCwCm8J9GWy3IpnduhT57HwJrZRFdcRGahcXkw
            SPoZLP9R+6zhiyBqlGyRqLZuUNMciZ1y2w0W9evfjLea5XHHP5PZwOOdQoAuIVfg
            0l4BnpxqblpVM9IAGvmlV8w8WOB4mSPuW2FwtzHaJGh2AynarovnG4xZw2FIMLKF
            fzGCXyI7KbQFsUrJrCabKP4nUFcP0JKSE/hRIrZlIbdI/jTvzWyj6wKRNXJA7fRy
            =L1tl
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2026-08-07T18:22:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdAcAPiOsJ70KU3qzOS/PUKI66Lhh/mvLdP3oUMchL4wycw
            /2vC+1W+dNSAXjfLmDz5i+BcyQMgSqhwkiHF5nZbFDQHbXc5Y9MD3cVj2/5Cwsfv
            0l4BuTwm+ErUZ4PcDC2nkU4PYM3y8mp6uN0gCrbyPMsyqfhG6Ma1svTC5EPem9qE
            YlCDhp9XuWlJoFwoaxa7pdueFpELP8Yco9b3nvQHN5u/OIH9VSv39FMHosMwgp7c
            =fFox
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    version: 3.13.1
