apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-passwords
stringData:
    passwords: ENC[AES256_GCM,data:dDXUN20O7KvMDsGBvvF5Xcjthbm1ev+J/H7029IuvdoN1ikRvQchkHmjqXtLNDKKowUiISVXp9/4CwUnn/K3SljzKa+12wp0wBYtuLZ2fjgeS7kxRaCjPExZe8bzVBQoEt5exc0EQCgj/GEuZku4UGZlEYxeSe26zIQ66p9mzlZCAZIxt8arqoelpO+7HmUUUCBja+RMhtFg7dlo3nC1lWGMyejlyAFPzXB0+rL776bgX0zXw+2JeTuge6/23/aOmnNhu/sJyhyXskpK+KCCK7H0YyAGXXJvYo0SxNbQ4pQhWYJC2iDkbmEYEhoZ8DoHcOuJYzlMqC2qaXXhBEN2MTCyD1256G9akka0OpwD2dpwnjRKZD6xY/av8Q3L+AyWcaxAtpoDHCE0sZYaCWnFLYGIxtJ0Kp+jrsC69qZDZw+Hjp6yD3hKBIstxIk3MOqdnd3wh0Ejs5ExqNewMlWDNqY6JwHphPnNZD/o1OjtPuP3A2tVNA==,iv:J2qM4TLuW/I0XirjBVGJJRLMTwHil9q7RArTWSgB6Ng=,tag:J3JLUAaSfj+3GqsLIyPRsA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-08-07T18:39:59Z"
    mac: ENC[AES256_GCM,data:4qJskzYN2BLJTyXizK/y/OCGMPJylCIQn3C3S8Ea6iU7RAcEr5pxTVR2IRgfyfhD6Z3Um5o0aakx0Pk1mXiaEjfEIjxaSAq78t/UZgOrUUQxGsD3L3IqT4nQTVJBH1W9Gnzxm+2RULq0wiyF10a6f4Oc//Gy3JZnzsGg7Sg5ExI=,iv:1VMLT1ZAsJHWEjKqIgJVpZjbL04yKmWJMFeoRzABvLA=,tag:2pYtmITgCRjpNzdPyTNXHA==,type:str]
    pgp:
        - created_at: "2026-08-07T18:39:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC4LUCsV/V+wSAQdAH1hWS3VAGBdbLFSKVFAT+e6Qe9UhgNMr4VUEmRbYByow
            3dtxaxlMJeeMBJxTJGRr5Ki46JWFWMT8akatbnlu09OzfhpNTu3Rb6MnN6kh+7nY
            0l4BB6ene3gBmJBYQvRnJ+NQ3bTe6iWs/QRXXUuzk3dHHr5kqqdZ8Wa26TPoBZp5
            fZPJ+bIv0vcCuQ5VYWb7j5rUvZr3CfVaHdkblQF9IQRiU7YUAZ62rZkLK4fcrUWN
            =gyjS
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2026-08-07T18:39:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdANcna8D50J3JwZWG8KGwTlWka6MIqU5H+z0A0AkYaaCQw
            ZHYH8xsiW+0mXh7rkRv2IHp9eIS7A20iFRTlVCtJ/YkKPa5jrch/LTpZCLulJlmL
            0l4BMxU1eSwyzfSrnOTPrzK+VLNILY6h7Y0g2yK9gYyQ++NurN+vLlA6/zYj9Mo+
            73a51uUraS1bzuXYSWU5Cg8ctwSX23E3EqnrPyoy5xlgvAdp96o3cav1yvkBXYYK
            =J2J7
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    version: 3.13.1
