apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-passwords
stringData:
    passwords: ENC[AES256_GCM,data:bwwC3iwwUbqDrbtHrGgA301iHwXq3UHtnv2c1NvbRccETXPn5Oauc4sKwUPxVde5QnUkGwZNxQf6EcRhWyAzs/a/bK2ZXAIZZbI1qankBAGEdt5V0hdIgOMfiPs4XfDzbAs+fMdiaXBwiBPpXPbvznidFHMdT+dJbM0QPDz+BPvyxwAA4x20N59lkXEChdiyVaVim3PDUJnlyNdXlxeTtPuCGjlrMlX9x/25MDJ9/e17Qu022AH35x6w7JTjqNc/CbaW7YEkijL2hkFBmmes+xJeF6vuH9XhWYB0K/a3ooSSEj5oAtXnXen20UevXCCYKpajIONxaPATYSufCd89BEpCKM4hCle0TFyKrHje04bxkgFN4l0FRawTGFu/5BlUM8QYZkHkBqblbIB71wea5wi02XmDqkN5Dpkmp5HBH7/wK4uifOe2pJVnK4p8ds+tP64HnUgZutQcwxLZ4DP5EUQvJYmnWC2kheriNijRLQw1oXgYMPqvpH2wjW5hmoISaBGH8Fkr2hExI3vG/UEyndg7+B6x9wgYTJ/Ea1NqCKNAa8vXG8PvXqvDcIiwzbYicnxbnYGbwF+ddlKeJDw=,iv:+cQ/ZzQJiNEfTRc+Qku/tRT0Ea2+b6g6Q2pqlqPvO/g=,tag:aDEK7sDKip4bZi1S9VtELw==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-08-07T18:22:38Z"
    mac: ENC[AES256_GCM,data:rPmh0D+p6jz3jNY6E598hd4jX5/yC/NHAB2WWhfUan+DuxFWfqJj+xqJSl8aDRB0SEDZbt1uf3p9rJBUFEWZpWe4ZBEO4sPLb3ggVNo/iQquXfdiEUfCE9o50x9F5KJf/AH7mtovZpSyM2QohM5upLUo5GvRmHrzFMs1GbMzxWU=,iv:f8pA+ZqyCtLAAbhbR0EwxR6Y2SKy92pBDEWxRgGA95U=,tag:uc+hE+UcFWCVp/pUNisgOw==,type:str]
    pgp:
        - created_at: "2026-08-07T18:22:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC4LUCsV/V+wSAQdAKcFspOJAk8YgyAqGVfH0MPP59U7glGsuqyc+kq1mZCww
            EWCQwCYwi+ldJ/GH93nlnXpreN0ZWw4SH6KEkJt8N/UVWlTRW9xb+t+QAxnXeHfX
            0l4BuHo+RqMDPlgXKOWuDOul8cj4cAeYK57ss3M2vuCZFVol7BttXB5pmg9GQUcc
            /l3a8F8EAfMbok4lcZFxD5dYP2ISoBl3ytj3oB426wPHZYf8YcbnStVd+HQszS2X
            =3qgo
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2026-08-07T18:22:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdAIef5n5JsE/eVwvFstBaVXz9KKDPJaxmPdv1UoyKCux4w
            nbaCaHsMTGJabrmSnMK8eyOoxhoBRrCZnJOFWoROYtlM0N/xW/7LflH5f2KOhx2O
            0l4BziuYdGH4UWMH7HgrsuFQ52lDMDph0XwxT4LO7NWdSttRnwWYzd2AKjiWl5Ph
            F9dLtUHurtBLUN57hZnIJnHvFNT7COxvk4Z1ki5joY0BcDFVFD1AzU4psZ9BBPD3
            =MAEp
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    version: 3.13.1
