apiVersion: v1
kind: Secret
metadata:
    name: router-wol
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:BWRAK5vj,iv:22PhVyUxfwdCLBBu0oa0VrYjvf0v/8K06XfuqeX3Rlg=,tag:LXBLw2p3T95+S/vf8cGRnQ==,type:str]
    password: ENC[AES256_GCM,data:KYBgEON13NuiZjBMC1i+JsFIjPR8nXeeQfB9X++71W8=,iv:/aBJSsxgyVBasmBP2puArZqmv9yE7e9EdvYCoX/RnZA=,tag:4QO6LQ6him9wYVkHRG7U8Q==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-31T21:00:56Z"
    mac: ENC[AES256_GCM,data:hrmOPhLq3fCr6rDMi26DPUnGoK9W+N0wt86FVphGgyr8tup3GF3+i+9WKEp/FnEPRe0g17yi4hqzLs4noCxCe1Hmaf4Qu68wTUmXi6f8cp93SjfFeD83gGQUmAs608267ohHv4tOaSOFQ7eYN46SgUI5zS+Fjrsr88LSSy+Z79E=,iv:l+Qlgn3iMP9t+V6TCvK3XpLG8xT8rJrWcCH+8WyEQBk=,tag:TDORAhyZfNxi3xnJaFdecw==,type:str]
    pgp:
        - created_at: "2026-07-31T21:00:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC4LUCsV/V+wSAQdAhdSlAXt6pY6WZBcyy1ePXi/CoYay3iedRL5T6IrhzSIw
            ytiYdscRphGl0VXsIhOY2NunqRj+r9thdHuyxBN8nOWlBZUgW31K+XCM7RRDuVfH
            0lwBBDe9aaoBzgNKXDgC+ktI0bC8pUJgi1U6GDd2yNx5WlKVOC2oXDrO/qdiboDj
            9FiPJ+X3aO8EEja/NVaxntnrDVa0xu/7C7W90M2yathvePA/EDwlHinGhchRDA==
            =th7K
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2026-07-31T21:00:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdA9yPV/nej5wZyhaQbVpXXiedDicI+t6RoSqXzqrJZ7yEw
            2z2n6s1hTPnkxl3xTLnUvSdHMGTW7Uej82QLj1EbhcDEYfwjn3cWlB+89n8+Bobh
            0lwB7U82T4LWMHMyshTGzNUCEDeIPbZWtTWUWRbaQtvXQsOPCP19UNUGYjJs5CQQ
            P4l97rCpUECmMBOAlOoxYrU6XAoxIBct/Cpd8f0F8le77u4Ql7uj+lxMnmv+eg==
            =slUE
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    version: 3.13.1
