apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-credentials
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:8GjNVP4XLp0o,iv:9/50HGL8APRIu+NMBZUFe+UQXCaiWhIXaX3c48+peyQ=,tag:hWZPtxTGKjyAkcSFlVQsNw==,type:str]
    password: ENC[AES256_GCM,data:Yqw9J9nkiK7urrIbZgy3Ao+y1s8=,iv:REWINq+3ZwnSnUjxlT96Js5lrI2Y6bKRVx27djbxAro=,tag:LWLmy/3hkRzXO4CKBW9j0w==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-29T18:07:17Z"
    mac: ENC[AES256_GCM,data:RVtUJ6nvBBZLK5/b6pTwqEUrMzpdjYwD+fR2rL9ZpZ0RqQUBblN8O45w0oCLye1vURGN3yMNgWl5hZ3FtQ/FLm8a0aoyxBDIkJUS5vO6CMMULFQmHjLJEWcnoREkyupZAa0y2gdUg/HSreUIZqM4kR4hxZBdm3QFqGSbJjfzd74=,iv:s+Jl1LHImRe/7FBcCS6QMc+OkReztDOFbgzDsviehOE=,tag:qmJIRGhlMIgKXjEGoyDhVQ==,type:str]
    pgp:
        - created_at: "2026-07-29T11:11:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC4LUCsV/V+wSAQdAoVnDQH97xoLPCoCHX0xcvYJ9V828tnc8AQyrGIBPlEUw
            8FBvafhnL/B2RZGl9M/jmkUs/NDzaV5mtmeAUeCLogViEUZlOONKSqx/SH+6Z8yi
            0l4B9sk7YEYMcNZpCuzked+xEsEnIxXV41AtnM7qOOp6ETyJH69LGHE4KJsGV+UU
            j13Q4vC1zSiAYqqgQtSOoM6NT5uisDPM2lpo0qO/8St/rynLmEk0DrG/uVeZM1IT
            =SPai
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2026-07-29T11:11:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdAucYX99V+7S5jea3vYmJ801JW9o7KJXGZzAnb6XTUXTIw
            F55SrCSGQWaRXZCqlCLoTdmBgB/IYZcJjFkndVa5Un90mN+p36w/Moba40UckQYJ
            0l4Bl27VKQEaox8C8UFWhIweThKH//zMCZkqAH1NbFe6AdA/RzCVlbUFPeV/Cn16
            HSx2hiS5dck6S4ICDmgcSTu7gTngfBpTMvswkH5I07hr+kcUFqwKYFJtpBmbH0ah
            =vNth
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    version: 3.13.1
