apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: authentik-db
  namespace: postgres
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
  - name: authentik
    kind: SecretStore
  selector:
    secret:
      name: authentik-db-credentials
  template:
    engineVersion: v2
    data:
      host: postgres-rw.postgres.svc.cluster.local
      user: "{{ .username }}"
      password: "{{ .password }}"
      name: authentik
      uri: postgresql://{{ .username | urlquery }}:{{ .password | urlquery }}@postgres-rw.postgres.svc.cluster.local:5432/authentik
  data:
  - match:
      secretKey: host
      remoteRef:
        remoteKey: authentik-db
        property: DATABASE_HOST
  - match:
      secretKey: user
      remoteRef:
        remoteKey: authentik-db
        property: DATABASE_USER
  - match:
      secretKey: password
      remoteRef:
        remoteKey: authentik-db
        property: DATABASE_PASSWORD
  - match:
      secretKey: name
      remoteRef:
        remoteKey: authentik-db
        property: DATABASE_NAME
  - match:
      secretKey: uri
      remoteRef:
        remoteKey: authentik-db
        property: DATABASE_URL
