apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: policy-blackbox
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus-blackbox-exporter
  ingress:
  - fromEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: monitoring
