apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portfolio

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- fallback-service.yaml
- route.yaml
- interceptorroute.yaml
- scaledobject.yaml
- network-policy.yaml
