apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyswarrm
  namespace: jellyswarrm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyswarrm
  template:
    metadata:
      labels:
        app: jellyswarrm
    spec:
      tolerations:
      - key: "PrivateNode"
        operator: "Equal"
        value: "home1"
      containers:
      - name: jellyswarrm
        image: ghcr.io/llukas22/jellyswarrm:sha-0643431@sha256:12319716879c6b5028da6c9cc75445502925f50d0be9653e7d27a2520f7cc196
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
        volumeMounts:
        - name: jellyswarrm
          mountPath: /app/data
        envFrom:
        - secretRef:
            name: jellyswarrm-config
      volumes:
      - name: jellyswarrm
        persistentVolumeClaim:
          claimName: jellyswarrm
