apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: jellyswarrm-config
stringData:
    JELLYSWARRM_USERNAME: ENC[AES256_GCM,data:kN+B2Y8=,iv:ztDB/ssmAUptDTpYuVgwvXV/D+RbAmU/aQ/xFhMxojE=,tag:4HKhR0S5E9kZQXwBFe7jTA==,type:str]
    JELLYSWARRM_PASSWORD: ENC[AES256_GCM,data:Dn/KBrsod6P2uYrOJZpIEQY1HhJzNhJd1L1Wyi8pnI4=,iv:v0fW5QstTLPw2V0uh1eNC8PlngNcoFER61MLjhq9K7Y=,tag:H23iuW6gbmra1Jz+fQGItQ==,type:str]
    JELLYSWARRM_SERVER_NAME: ENC[AES256_GCM,data:Qa3Fj4OtA9zR,iv:vraKbZqETfMhniPMyVZNSk9HOdstW4lr6F5fD/tZZRc=,tag:eoqP8nwYsnktTePRJkQ8CA==,type:str]
    JELLYSWARRM_PUBLIC_ADDRESS: ENC[AES256_GCM,data:abDPG1blQ/GQIgj7,iv:+9sH+vhA18ULmAoYHWyPLhJ+g11M3yODTHZZpJHwxuw=,tag:Yt8YFXD3kRDh5UZD6Kzmtw==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-05-20T19:45:58Z"
    mac: ENC[AES256_GCM,data:Dgbi2aeYiEMVDsPJ2rjfPTgBTvB5jojVVSpHyyv85nLHbcGFAPnPnOlZ4XXN59KJ7aFZCCVOkcGSjLkuFVRDHdbwzuII1eTS5tuHicuOwRDf+yq4myk99hRsvxYOtMUc8nRVli25rKiEXKjhH8wZeXuNkDV3YdHBJ/TKlQIqZIU=,iv:xfPSmdemufT6ZTJg4QXLP0VqQ3N2KTtlkNJUZpj1s40=,tag:dUXEDIqm9neUxqLQQjt9xA==,type:str]
    pgp:
        - created_at: "2026-05-20T19:45:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC4LUCsV/V+wSAQdA2JJcfC5dGA9lyOEl4yN8m7SoqVXk0CHzAMUoZU72k1ow
            BXio5rWCOfRVYusN4EvG2a9tP8V6L9Wve9TMHDNNALvG39vahh0YNZNsxzokQg11
            0lwBrg9YIhpnEwttGdqmwgGJNiXfsQ/fhd4/KeDodIFQsrPQBF0h/xY3Ba2jbNOF
            tKR1i+rnwYfACe8TYX/exUiimEBUKE0d4FlVP23riHE8TOJrpSBNsNDuDIgdAw==
            =RhmU
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2026-05-20T19:45:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdA0kXQo9gk77WhbpNn4mr4RylIHOZik9BvquIiw1LRVEYw
            xnIJHqnc6GE73pDf6FNe1Iu/dQyAIMWlN3zFZfns/972gRVp6mMY9+mcbqvYt/dM
            0lwBzW0MObil4Af4S2vGdIDIHWMD1Rffczq3P5n0N2940XHlfjebfxAvysbl26SK
            ds+WZneg522Xdr3sxaw6jt8U1kM+PJUJKpN9ZLCmlIcHBvAiC0URl1LRwy7bRw==
            =xXTh
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    version: 3.13.0
