apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: kube-system
  releaseName: pck-du3hdym-addon-cilium
  chart:
    spec:
      chart: cilium
      version: 1.19.1
      sourceRef:
        kind: HelmRepository
        name: cilium
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    cluster:
      name: pck-du3hdym
    ipam:
      mode: kubernetes
    ipv6:
      enabled: false
    k8sServiceHost: pck-du3hdym.api.c01.kaas.infomaniak.cloud
    k8sServicePort: 30282
    kubeProxyReplacement: true
    routingMode: tunnel
    tunnelProtocol: vxlan
    MTU: 1450
    operator:
      replicas: 1
    serviceAccounts:
      cilium:
        name: cilium
      operator:
        name: cilium-operator
    bpf:
      masquerade: true
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
