apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
type: Opaque
stringData:
    secretKey: ENC[AES256_GCM,data:NMI98hZf85UTXwXatT7NO89GgzM=,iv:hLi5drw2c2H1xobBovi2m3f1nS2IBDM9rZvRlBe3Fz8=,tag:r5aSE3u+dVqJN17lzSZnfQ==,type:str]
    emailHost: ENC[AES256_GCM,data:PyYvt0nybxfDdFVk/nQ=,iv:M6d47ckOADwwUJwHefpDSEt9VBnoRoc6P6dNgnLHi8U=,tag:p17q3ha5uXPwfxJ9E9rsaQ==,type:str]
    emailFrom: ENC[AES256_GCM,data:W2ZuVMq1+q9rhcd1slPzWfOIbQ==,iv:UCKHUfLn/JbzExfANEqIm2iTMC4lGU1mkqA/j7jOvl4=,tag:/a0vGKmR4ZRUaGEpmfFxhQ==,type:str]
    emailPassword: ENC[AES256_GCM,data:8NCQsoy7ABt+b8OEFOBTUFQpQow=,iv:q2xKbwm+mnWIyfTMGS1nLEAAaXLg9v/dZWSwkS3JwKQ=,tag:ic53COkYCgCh0yKAqFHu+A==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-29T18:13:39Z"
    mac: ENC[AES256_GCM,data:19K6XoWboKCRrrnufr7td71nLwTO/w6GNN38BBRVTDmSRRXK2adLetGR11Cgu4RezgTHJ+gv7s/i1WM6AjswBAvghWAnLhwt9hYMeJUlPxihCZ2Ixs5SGdFDGqmPPYWhflW7sWYQgvQYoS45E66cV69HF/pbE8siTMq1ZdG6118=,iv:ouLOnD84zGyjOtKr3fHHH9Bdgct8eiEpE9SGgMoXy5k=,tag:ZWpl5HddYq4dbZjWQjgu4w==,type:str]
    pgp:
        - created_at: "2026-02-01T17:22:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC4LUCsV/V+wSAQdA+GyoSn5ro6JJjbuuOn5ORbtBwn01GCieJvUAwm54ZSMw
            +p2oIYkP0pHXkBKA8mwauTrsKVXOhQ/p4chJbaVKmAINg2S8P9lktpJOVrJ8B98k
            0lwBom8rMWUuaK2EkIq5xPJn8DujXenk7joqVud83Nu6fYVh67FaAU4Au2Y7vYdf
            PB+utyU/MxJqxhBkdHfe4oM/yYGAjUMWV1bwFoszdiBBHTUxjJVOX0jMQRTCZw==
            =fEKn
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2026-02-01T17:22:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdA+o4W4H7Tpw55EruPS1VDkwzEkJcSMcYZDEOf+UqUW0Mw
            p578WRk5ENecFQuVqdYdtJ+3Ywo3qzQO0fakcbnVcRk/onhXHgwYj6mlDRZrOudp
            0lwBLkuBVH0l6UnSufgUDD3TkS/yGrolskibPptgPxZ8Uy+HTcW3aE1ZNMHrLk2e
            xxxIfWypG24w85tUHJJFVTW79X7I6BulTbHNww0ti4eqYnycpCJH9VsPul8E0Q==
            =VkiP
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    version: 3.13.1
