apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: policy
spec:
  endpointSelector: {}
  ingress:
  - fromEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kgateway
  - fromEntities:
    - host
  - fromEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: monitoring
  egress:
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kube-system
        k8s-app: coredns
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
      - port: "53"
        protocol: TCP
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: monitoring
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: authentik
        app: authentik-outpost
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kgateway
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
  - toEntities:
    - host
    - remote-node
    toPorts:
    - ports:
      - port: "10250"
        protocol: TCP
  - toCIDRSet:
    - cidr: 0.0.0.0/0
      except:
      - 10.0.0.0/8
      - 192.168.0.0/16
