apiVersion: v1
kind: Secret
metadata:
    name: grafana-values
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:g+bUNEYQYjsc67lh6Wtn8AEdGNovvYQLFJUMo+g34sqTsaD+SaJTB4fTcbr31hgWJxWY3vsjr/97kcAdPCRP5Z93g6SZmm+5O746r7HCx5cieqq3wVmTrY49vvCfgHQj7b8AXlHUeGHcvCU/V9Tr7+1XQMIX19ernA587bvceNaChNQJ24aZ2FoHVx01/LUJ2cxs8Uz5oiAlwLzR814lH5D6E/awLFMzcJvO1fp+TbTW7B4V7EfCti6nnz4vcZooulEDMCo4b7zwei1r9IWKFyw0+sSuevG9B9jvh2P7WeqnZ3BGvjxi5OHJBbwrSTc2gIl+uXm2oxc4GriolxpfqeL4bRSeuPa4prUpHX4lsLlzKCnhMzWvbPpNNc//Ol7Bf0PCfi+asrLrnCWqZi7bibGuzqGgohTlZciOZJMeWAaZ5/OwP7a2/6rzDltPCPg22eN73yFoFNhCL5kDT20t7K4S7VUP/10lm+KDOggrcJtjbQBmS8PHTuhd646MwUjC9N2Oor1UczdtGe7J+E56w/yHRa1bLbbu1ogEC+OoQpTKe0JUZHaOS1BTaF7QHIhAckKk+TO3MO6JcrL0nND94ib9J4/qTTF8D+H1VCrFwFLKsWiXBLmxUvZrwcrZ6LTZyLfaO150CVGLrvnN0mxRKiVSw0uZctFJ3FfD5Kf+IiTSiuuM7dwSt2O3vh7+g3hMpcLjQCzniET/P6foxK3H3SHTeOXSQeuXSNeDhHKg8LTdLuapDNT+gBQVmfzueY34z7gxv7o3dMILFUwA12xP8BhigYLTT2RiNDHwN87owVsYWbLAACz0PW+9rTJZOYCfnLQYjm/s/LNkpHsXg2AxZj1pBMCcwvLYMWJx6YUSdq61s35cLXfjS0KAfG7ATkcv3gurQXr2K5ioK7dRvbQxS7ghU0N+vp56awvTx0fBFA2y/6o13vf/W/y3qsXX26yCCom7TihQ65kPdVWCBenWNE6ThPufQ41dqZ12DLM1LJPySMTCuYFb4L47a4Y2YfZ9/8BFU7pp1pgK3eN1M//JZ+Z5TSX+v53/j+6R6S/hFlhPR7S+3p/SLCo4oYPItlwLHF1uwHZz42+AepUzHszJtWQr9QHDH5kE/zQlrX0N+bt2ZlY3UsWcfXg5zUiuPAY30vKy5nTANht87ZeVuDghDdp/LulKR0AEgW96wEoT8MMq5yeaHEiwx0olGxmC7WZ0bmci1vjrJWj8ZKcgPiYPAroAOzXCplVkIsDbHLLr72nJ4rvu0uvRH2YB7yf1k45jRFWJL7zPJhQkr0yA5vxIGNdHJGjYSLKW1KwrQv88/n7Ct+RiLI5nsoyL+KRib35FNgLy8Qi1imrkGzkDCA5Pr+4nzQ5hUgacFw4/LD5/EJd+iKvhxciiFM2tXsQ7SwInzGmzXzozkFCsUZL44YhGKvbk9QNywEP10wUxfH0qJ2420Bc/Ak84g4c7v0fWki/lYiBDf6qdSWgOG9KncyaQWqjHznicAwHabaJRAdbksw+lsoV5HIzn7TmhxE5DrGPT7L/bfz/ajrE4aNmYLP4EtyYZRDqQLZofUizZcgxAiYD2sQh39Mw8PwgluAeYBJUoZWzyHIGuZ6phJ13qLPJep50nSju1QCKwdVgFG4G80VbyDZR34MlDiOMeGq9lH8AyQ4dEYWcy3XRTybFgUlIg5I6uInw2cJdSNvCP5z1Qgm+RtMuq/JbzAE7QnRX9yZ7jWGPNjyQ4hX+BD4eyOa/RQZtddOnfVcv/KApkCa7ySHNqHOlqnJdKr+HSOy+X3amWP6YR8OQ8aIQs4LqWqxPSR7B+CojaAClEi4FUz8YpBNUg/096w8A3jacKLwAFn0HkHM/BwcTvcuNiy/jY224DtcIqONlRIPVsNBDSLZNfauFXMqUaUgyCvxF/8t4/ZSocTctb0mEjCGAwaVtX/8nLGEEA8xWJprtnFTWH/FdVWR6ujgunDMbWUemvpabpkawhRG+pxHEughxLT+s1WKhH9UqwREFYjIrcOQWaqHmMFrCVvGIjUxVL5Jxy/Lts6CECYXsQlJaID87xXz5jJKjYf5FBDiF0X6MNdb6Wkj0wmhm5KKsf0yk/gqRFE6vH/XJWu64yjbZKCbetpdqlsmanvqtf50NqFBvHGYgVzVrGxtp6WAHShkQB2Z+vOFI8cPb9qcUcxiku/lkvVDZeY06OUrgZIeUhRvplO9sCOjMPKb9XSx+7kNW3tUpRptDZxxcjDXyFsaLJV+cS2eBpVMznPXyf0upYidFpDOW6/And8E0J4O31Jsg6aSiU9ki1RA==,iv:xCZPruzy544wOvQspu+qALCBCbgob+wniZhcdzXygr8=,tag:7uef3ZHlFK9CXv+7wd5v6g==,type:str]
sops:
    lastmodified: "2025-10-01T21:03:53Z"
    mac: ENC[AES256_GCM,data:YjzH8Iyze5xZCWZ9NYvBvVsnTFPRBE9luTDKvt5gu+yiUPSZssUgIa9uYnUQw9eoL4L0y30Uc/8SplXO+ANfleTLdusWL6JA98m9kIQZdBsp0sHZqNdgp4or7CWEaIUOrMtKVUOBqo8P6rAIH6K/NVpqyLr5mE4P/g8VIbPTRvI=,iv:9zCS0slL/yO8Tk9HbIGjOJktG9L0Okjon9A/po+9zRY=,tag:zYNmIQRLEcVD1wOogUfdgg==,type:str]
    pgp:
        - created_at: "2025-09-02T21:51:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D6rJQTzBUCVESAQdA86GfbnbBrWbmDrF1OYR89w0TSdcvlDpwIEN54h5yvXUw
            3A3i2y5H2Up3k5EmIixoxInjP1ZsL6oKZ7NXtS3WVvuMmNJ2KvsvdD8gbSlW9jJK
            0l4Bo8CFhb5904U2n9CE+EAMg8L0HQ+AOHu1x3VrcMh5rx5S6jtmcYEvC4bAKoKB
            dnWpoPqpjM2UsckDMVhWBuG6EqfJghUetKQaunmtEs7JQnhxX21MPSc726I6pHUi
            =xIIg
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2025-09-02T21:51:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdASrc+insvacs5PlftFj4aO/j6bmaCXE38dSUhQTqJRksw
            P8KU6QWUOWba+8l5kBnsOw8Yc99FqPPMsmHSS2y6LDSLZMSE5sthpzOCJijkJNdd
            0l4BYcJkOhaY/0ssfQYpQ9I6e5esPUsCaxPpp/Ohq6eeJ1EI1mpV4uL4vuktg5fY
            oU0solnjl3PXKB3APvUJRaYJmNqs6oEW/intTRc02Acxe9lIEZl/SL7hce9+E7t3
            =G2p1
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    encrypted_regex: ^(data|stringData|secrets)$
    version: 3.10.2
