apiVersion: v1
kind: Secret
metadata:
    name: uptime-kuma-db-credentials
    namespace: mysql
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:6QdOsPUGaOtkJXuKEfnT1PwiC1qW95Ewh2Y=,iv:x0p9qGsO5QxFPfrmuNJcJqN5nCvNvLATJkqMkFDYyPk=,tag:TdH1oT1/KJKtUrzQ9+kXEw==,type:str]
    password: ENC[AES256_GCM,data:jvnGqN48UkbdftPSr3b6eozG+hIM3ELynmWwSLPZO2AGIfAf74TK6Q==,iv:+AebkhNnXcVGYSdvc9ylWm3Gd05MUA4zuCh5c/oNNig=,tag:ImzDe85dIrgojEjsa5+usA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-30T18:19:31Z"
    mac: ENC[AES256_GCM,data:B5b3uvxYyBuIeUhkP0nltNKmAW5ECD+XPjdYBJOR4bK/GImFuUiqV5jOyqntHISmn+rB3O7LnKQDJpJFeOVhLBF3djmigBhKmaGcfE6KbM5vHzRsJNleYb+5tu+x9xa1pXpUhP3SlZomQSmSXB1h1NcgGLZFrcO1GAyRA3urv3k=,iv:SBPc+0c179Nn78OgY2ZgD16QhcQWanuUIooQ4Gnw6Lk=,tag:vfRrxcQOGNguqV3gkSU6dg==,type:str]
    pgp:
        - created_at: "2026-07-30T18:19:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC4LUCsV/V+wSAQdA88qAJUVl8McEs4ToNXzrv7GJFdQBeOSbFZI79Xop+SQw
            NJOAZDgnWSeKWYdjlKjIOJ/ag4zVgGKQE8V/cYrRoLkBV9KzXTpZwMI5uG+6Dw0L
            0l4BOqfN/DUKDDPCErdpnUFJB1dO8k9x/yh2fLQpw9wZigseMpgM6DuFm9ZQL+wz
            iTx1lgOyFaiYQ7Cpi5YgvJJSu8+u0zpZhWzco22HQzUZwClr1o7RoWmWWxQ8T5Gk
            =mAvS
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2026-07-30T18:19:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdAMuWk5W/NFY3PUwSS6733VlYQ5kLsHa6BlzilXcgcRQgw
            WunIpMz2nNPdcQVw5poWzdaMtvc97YLkKX9U9ViS7aAoBA7S9jkvvUsuaVpuUsOL
            0l4B7Ud3Wn6+lsI6LQF1BeVUPIuZEIYsdK3JBsSv/GjYweS0EoJiMD9VHoT5s/wn
            2v0HlI/NCx7xTWhJ5VYOS/vOR+QHDO6udpidwh7OFvwke0WvdQvaWbp/GQXQxW2h
            =eJeo
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    version: 3.13.1
