apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  annotations:
    k8up.io/backup: "true"
spec:
  accessModes: [ ReadWriteOnce ]
  storageClassName: big-pool
  resources:
    requests:
      storage: 200Gi
