apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  labels:
    recurring-job-group.longhorn.io/immich-backup: enabled
spec:
  accessModes: [ ReadWriteOnce ]
  storageClassName: big-pool
  resources:
    requests:
      storage: 200Gi
