apiVersion: v1
kind: Secret
metadata:
    name: sysbox-registry-secret
    namespace: sysbox-deploy
data:
    .dockerconfigjson: ENC[AES256_GCM,data:YZHFTXZ8zWCAPZMQINjapH79zH0M0sc3wWH4Aule1UVNBJO4BP+03BjMabuHQ0GdDMIR70VJkE4tFHsXbOa4ik03cqom5dJ93CFaKeAPCBIM5YwJqZTVl6wR3almQ6YT7Rys97xTJqnlTvIHJ3aeX/tGqyYyJUFThfLPH2ZA+JTMNbIF6NveMGCdYf9K4kM/oiaI8WabVdiAeN6uqeq9C5eCQVeCX9XdFRTMLZdA2JzNkF9czBwf2LZOUPO1CLCwaaGYutGvXIhldnvs6/e0RBwznPSjm04w8qJ4dFJJLyigv1Hxb2FPDQ==,iv:EBQYfn4vv8gZlYeoX0FKpZCE1/0oFAP6ONvIH0aqpsc=,tag:s8l9HeuvbZEuJXi3f4OMFw==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    lastmodified: "2026-03-22T14:17:43Z"
    mac: ENC[AES256_GCM,data:rjUmybGtCDvNtzw2tEe5Ewqh7eK93Ef08jCGx5TdTAfiyp9t8QRR7kl3PIQX2TVvvdmUA0/YY4aZ8ZHBvVbikiXGiWbmqKBxOCWox1nQrrqp2He842AICFmyulgKmvv16wxMC1SCRSSP+/zpDQ1uZXYSIC+eJH+/vjFSmbqGPqk=,iv:SFehJmN7F4TEj3Ef8T3rW7559gys6vL+fW8yRGj3gJo=,tag:b79cVQqpyWBl5zgijJqofA==,type:str]
    pgp:
        - created_at: "2026-03-22T14:17:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D+ngZduHpaz0SAQdALQg0JGY5dpXVOepfC7CYsX4rgWv6ceJ5bNhwwK9k00cw
            fpROL0RIizOwI0Yjp/DeP9NQ9A1PSoLFv5OdM1WR0DmYXc3N7ORkTP2m2REQUM+Y
            0lwBEK0YALFzIDW3S1IZL+/JnIOF/rUyzEnb79HZ5vS76Sztsw/bWsMhTmu08Jt9
            XFuSR0m5sJ6oiOQNHxv/MhQGjYQTUte0peoBmg9UPvn3JoGLvL8i/p8EjiGwcg==
            =Js5T
            -----END PGP MESSAGE-----
          fp: 5A2F2F5CA8E4B256D33CC201AA64751E0A2012EB
        - created_at: "2026-03-22T14:17:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D0Zv400BbniISAQdAQbX8gUgT5yHnNNu2hyHvwnipqmaNE9Al3KlS5XcHFCEw
            ENzHEzh38WV644y3SXMwGYie6m75ux7QyK7I5zYvug3EeOFNd9VISmHGup2BEGf3
            0lwBYSFdUMHVU3/+M/qZvTJ9XCAloILYQ/01kkAN1iIJKDz/OI7T+U+2AXGj1AnU
            2wTP+p8LqMKeSqzI6yJMJaEpwxqRZ6aS8uu1gkfK99LxH5qi07VHkoLEjie4bw==
            =D21r
            -----END PGP MESSAGE-----
          fp: 1CA6FD0C5D933BABCC437DE6F82851576D47FAA9
    encrypted_regex: ^(data|stringData|secrets)$
    version: 3.10.2
