#!/bin/sh
# Renders conf/initial-data-sources.conf with the two root passwords in it.
#
# Why an init container and not a plain ConfigMap: the file has to contain the
# credentials, and they are not in git — they are generated by CNPG and CNMSQL
# and pushed into this namespace by the two PushSecrets under
# platform/{postgres,mysql}/applications/cloudbeaver. So the file is assembled
# at pod start from env vars sourced from those Secrets.
#
# What CloudBeaver does with it is upstream's own first-boot logic, not ours:
# run-cloudbeaver-server.sh copies conf/initial-data-sources.conf to
# workspace/GlobalConfiguration/.dbeaver/data-sources.json *only* when
# workspace/.metadata does not exist. So this file seeds an empty workspace and
# is ignored on every subsequent start — after that CloudBeaver owns the
# connections, and it rewrites the credentials into its encrypted store the
# first time each one is used.
#
# The practical consequence: rotating a database password does not reach a
# CloudBeaver that has already been seeded. Update the connection in the UI, or
# delete the PVC to re-seed from scratch.
set -eu

# The two characters that can break out of a JSON string. Passwords from both
# operators are alphanumeric today, which is exactly why this is here — it is
# the future rotation to something with a quote in it that would silently
# produce a file CloudBeaver cannot parse, and a server that comes up in
# configuration mode with no connections and nothing obvious in the log.
json() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

cat > /render/initial-data-sources.conf <<EOF
{
  "folders": {},
  "connections": {
    "postgres": {
      "provider": "postgresql",
      "driver": "postgres-jdbc",
      "name": "Postgres (cnpg) — superuser",
      "save-password": true,
      "configuration": {
        "host": "postgres-rw.postgres.svc.cluster.local",
        "port": "5432",
        "database": "postgres",
        "url": "jdbc:postgresql://postgres-rw.postgres.svc.cluster.local:5432/postgres",
        "configurationType": "MANUAL",
        "type": "dev",
        "auth-model": "native",
        "provider-properties": {
          "@dbeaver-show-non-default-db@": "true"
        },
        "auth-properties": {
          "user": "$(json "$POSTGRES_USERNAME")",
          "password": "$(json "$POSTGRES_PASSWORD")"
        }
      }
    },
    "mysql": {
      "provider": "mysql",
      "driver": "mysql8",
      "name": "MySQL (cnmsql) — superuser",
      "save-password": true,
      "configuration": {
        "host": "mysql-rw.mysql.svc.cluster.local",
        "port": "3306",
        "database": "",
        "url": "jdbc:mysql://mysql-rw.mysql.svc.cluster.local:3306/",
        "configurationType": "MANUAL",
        "type": "dev",
        "auth-model": "native",
        "provider-properties": {
          "@dbeaver-show-all-dbs@": "true"
        },
        "properties": {
          "sslMode": "PREFERRED",
          "allowPublicKeyRetrieval": "true"
        },
        "auth-properties": {
          "user": "$(json "$MYSQL_USERNAME")",
          "password": "$(json "$MYSQL_PASSWORD")"
        }
      }
    }
  }
}
EOF
