apiVersion: v1
kind: Service
metadata:
  name: portfolio
  labels:
    app: portfolio
    service: portfolio
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: portfolio
