apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hubble
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: kube-system
  releaseName: hubble
  chart:
    spec:
      chart: cilium
      version: 1.19.1
      sourceRef:
        kind: HelmRepository
        name: hubble
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    agent: false
    operator:
      enabled: false
    cluster:
      name: pck-du3hdym
    hubble:
      relay:
        enabled: true
        tls:
          server:
            enabled: false
      ui:
        enabled: true
