apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/
  - infrastructure/cilium/ks.yaml
  - infrastructure/gvisor/ks.yaml
  - infrastructure/kata/ks.yaml
  - infrastructure/longhorn/ks.yaml
  - platform/cert-manager/ks.yaml
  - platform/certificates/ks.yaml
  - platform/envoy-gateway/ks.yaml
  - platform/external-dns/ks.yaml
  - platform/keda/ks.yaml
  - platform/cnpg/ks.yaml
  - platform/cnmsql/ks.yaml
  - platform/postgres/ks.yaml
  - platform/booting-up/ks.yaml
  - platform/envoy-proxy/ks.yaml
  - apps/cyberchef/ks.yaml
