apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:jkcEvKSSZ+GBpOmfl68v3khwfv0WMhgZd7+v5he6HPl89wyZ3sorxYfFL7QXoUpYz7GU6V3gKYVGXCH3e0E1zw==,iv:tYyFNfJ3enr7eB5OOw67tPrzxpmqna++0CXITb8b0GY=,tag:XA5QH/gJavMVibbSEG+9rg==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:Z5mil3NP7wmGGAv16Daz6r2QZBBHXSqSoySywyG6tqXAFUzG2K0TCrF8n77xlyEaCo3h16V9wAeyo9nXvXTBDg==,iv:1BBkl3TziG9tY/D9zW1j1ANHNSqZMrR86hMrQrKG2/M=,tag:nkdN0agQXv/jwlI0eobtyQ==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:FOj1jGZ9FE4s+x3bUelYDeo3xZIIro5lJkd7cHXU7H3sp5kGMZWT+B4JW5nNw3Q6IT/nGHYs7KP6BCHtb4UoCvqQ5IJT7XgR5zX25VZo3Rb+Gh3OMCXAy2jzK5XgO25bViGuiSbrdpF43nYp3fO2V8b1EwVYUMPd4cLmiFDKp6nB93KR07RESlgMPrbtWyQ7/R/P3rivitL3gtloUFoJEynSyMJ+JoKQMCzoPJLnStkXb7Z4QZ2GxqRqBd424EsAw8os/slnK9H4J1hbOkW1f9fu6yA248QB9xkKqLrxJ/YTlt/uS+RSKwLfyrSF0SfsX5JkXpEXdZlk+4BlHXIou41ix6p0a8fSR+w4k/uQ/M26EAHIkmN6mbdVI5LuJH7hNFYmhHIhVWqNopYcdmzyNI/YMgP22edyGwpT1KmIgLyQmKSLK1CacjW/RlCTzduylIBpDd5Xo0U2z9o3tHLWdX5WQTPsy7jgE63PvafzSuQXNrZ2426A1zwQn+Ik84bdVcQirrokzH9nYpczSuASu5J8G/xCWigas/PtEAyUrrf6fYuyq9sy90SlAHzFU4ChCVm1Lx7mN6wJTMsYUX/4T41YDwwFC94hbHZbSKWP3hL5RDtwLn+j2tvRCa/pRFKjrsE+fVUds7RmocPKgF8Mz/4IAK9kvILrhuIXoYCtfz9GvXrpHU8+hu69im7e++F+1QkaVOAf+QmofBWts2sn6+iatMhRBQPZl/qGpOt6BY1XFbLTE+68uFviC/T47AuWoHdIasBebu9kV0WtIGVw7ieAVWs8n2++PJQIDrPqfYbf,iv:eNtgscfBsqlAVR0VBeNYDKWOtTaOsMuzrTzW3/N+TQk=,tag:P9EkeEj9Cz1ERFF3JzTDfQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-30T16:17:36Z"
    mac: ENC[AES256_GCM,data:OWvFTiopbB/qUV9m3FI9s3jFdxGWtNMr6QepDbK5KjiGvQJWpW996XkcDCWRzpAH7Ts7S3DRmIjc0dWgd/FNrCadKanm+4o3q7EI2YXmN4KkZ5/LIidDnXI4PqtMSJeqmh2Loc4t4vhZg2Ew/iprgtoNeHP3JL4QB7U8/ZMQn4Y=,iv:1SbB4FJLAVEgMmNnxb9MhOrYv+hzrxiiqxra72F38/4=,tag:zmc1J80yUAhOOZ40cT04mg==,type:str]
    pgp:
        - created_at: "2026-07-30T16:05:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC4LUCsV/V+wSAQdAVWRO5BtYkgLMlPcSPsyQ81u9AjOJEohKYxEvRe2i+Fkw
            EeoZ1u5fPqxp/QdzbX5BINjn+gmzB2fvc2r9Or1hnwj1Y4UHZDjfMSBJW4LK3y4m
            0l4BJeqViyuNnBazjh9uI9BwfG5UEq227R/m5YNSDTAiycGPYCNDAlTzeMEAEAMG
            h7cipwahiUl1SuzXEWnuZ1DRTRaYEPnwcCXF2EyN5vws0dn5+Pfw0LCspXUzWy/h
            =Lk8i
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2026-07-30T16:05:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdAcZQA5ENGp2eg1J7CHo4fUwiZqe0kZuS0pECwnIgxsh0w
            LmOAf7basKhp8uDq+S2CaifkXCWn6wDEGrkEuJNrFXCJpG0ljQtB+9uQurh7qT4C
            0l4BBZQUNsxN2P0smoUUp8dqCZMUXHNqKgTifCN7gX3nSB/2zMAKrgwtkBHlvfFl
            6IFDfzZDExYKjciSpQCBMSD+ZN3I++EXEVu6vm5kL1mwUzn2TOMMc+KZqBNbyrTc
            =h43k
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    version: 3.13.1
