apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: vcluster-udp
spec:
  parentRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    namespace: envoy-gateway-system
    name: envoy-gateway
  listeners:
  - protocol: UDP
    port: 53
    name: dns
    allowedRoutes:
      namespaces:
        from: All
  - protocol: UDP
    port: 3478
    name: stun
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: UDPRoute
metadata:
  name: acme-dns-route
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: ListenerSet
    name: vcluster-udp
    sectionName: dns
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: gateway-system-x-gateway-system-x-uctf-mgmt
      port: 53
      weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: UDPRoute
metadata:
  name: headscale-stun-route
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: ListenerSet
    name: vcluster-udp
    sectionName: stun
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: gateway-system-x-gateway-system-x-uctf-mgmt
      port: 3478
      weight: 1
