apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servarr

resources:
- nordvpn-sops.yaml
- jellyfin.yaml
- sonarr.yaml
- radarr.yaml
- prowlarr.yaml
- bazarr.yaml
- jellyseerr.yaml
- flaresolverr.yaml
- torrent.yaml
- routes.yaml
- ingress.yaml
- network-policy.yaml
