apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m
  path: ./ng/flux/platform/external-dns
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
