apiVersion: v1
kind: Secret
metadata:
    name: sysbox-registry-secret
    namespace: sysbox-deploy
data:
    .dockerconfigjson: ENC[AES256_GCM,data:/mVFIIWusqXIvjPzsL4CqLl6ZZe3Jhc0CX1EyjoUWycl9brhZc1qOug3QI8AXBilzuENl2WFqVaEt5zHNiw6lot+H4gIBJ0rsK5QTHAnqZ/oXbCPRXTJCHEBjM+Xye9xTBSOhcn5llqCpcou4NhU3KIAzXRR+ciHmWRTKZsZyDAa1NP5ngJC3bU3f0I79H3Ez8Hjfwnz24RhBDM7PhSKewSnUd3NS3jTTCcQ2KYjAchpKUxq4UYgRg+HN+QalW3v1BO2djQYdgYIcIthV0gQODNqf6tl2cGmI0Tqwf+TiAZcAEfH1OboxQ==,iv:4ZgFH1Xg3l/67tLghPSBlMZAf7rGIoZpyBN8DViFPRM=,tag:KovE5s6gm8K8GRkgxvaUPw==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    lastmodified: "2026-03-26T19:00:38Z"
    mac: ENC[AES256_GCM,data:38YohXZNbjcVcFq4NUh4/b8nFdn2Wa7TurVFNP0XZ3FGm89IwYDFzKJBjT52ZoHGuLAVJGS5C/TosfcBHA8qM5esVJ+kFyDBDmnJmuHYJI25koq7a689rDA0dHIa8e4KdRRGcTGoxsZAYsDHB0DYPozdvMhQ+MQRzpjmgF8cppg=,iv:F5UYuJy2OtJMKJBDbivnvXf36Uz5Tj7G35NbvlA/Qgs=,tag:NH+M2PRqtqqb4xF8wFuLXA==,type:str]
    pgp:
        - created_at: "2026-03-26T19:00:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC4LUCsV/V+wSAQdAEFeumhRncBKaTYqKsM/few9d2kCFSmgp2UFg5AfJ+nsw
            JVCEl3oV1sVj739sOp8jny3xmFxnVEA2D59M57kqws/h/CnqvFElBGIaMzwhxtCC
            0l4BWOG81fy/heOzsnt8zpT4JykkewB2/k57TaKNA7fnRVNjSRCoyP8/W8XH95mX
            TmFDrCqlbuy/6EI95jH/kAxPPMgpvOQ4Gh/rM7ACv70BYo1BZqcEXfuXvg7yXEdb
            =FybJ
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2026-03-26T19:00:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdALPrhXARUGT9JMxWncagBFwz08hkfyixUVb04T5DVm2Iw
            ba8PgehoiYjkOqwna//rGe28vAPucxwS3ez/jW/c5NXyfyseLNTpoL04DzUuZMTP
            0l4BcXPOUF1hr99dM/ScR7LqPqqNVHrhiZKh6CQgMtLdjmoAJypR6C/NX2DX3eD6
            EhoVJR9ZPaIS/R97593h7ZRaW32cGqqjBN94FG+Qj9iw10Xv0qG4f5YIlbmR+Fxm
            =j3v9
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    encrypted_regex: ^(data|stringData|secrets)$
    version: 3.10.2
