apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: talos-backup

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - s3-credentials-sops.yaml
  - cronjob.yaml
  - prune-cronjob.yaml
  - network-policy.yaml
