apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: immich-db
  namespace: postgres
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
  - name: immich
    kind: SecretStore
  selector:
    secret:
      name: immich-db-credentials
  template:
    engineVersion: v2
    data:
      DATABASE_URL: postgresql://{{ .username | urlquery }}:{{ .password | urlquery }}@postgres-rw.postgres.svc.cluster.local:5432/immich
      DATABASE_PASSWORD: "{{ .password }}"
  data:
  - match:
      secretKey: DATABASE_URL
      remoteRef:
        remoteKey: immich-db
        property: DATABASE_URL
  - match:
      secretKey: DATABASE_PASSWORD
      remoteRef:
        remoteKey: immich-db
        property: DATABASE_PASSWORD
