apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirlingpdf
  labels:
    app: stirlingpdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stirlingpdf
  template:
    metadata:
      labels:
        app: stirlingpdf
    spec:
      containers:
      - name: stirlingpdf
        image: ghcr.io/stirling-tools/stirling-pdf:2.10.0-ultra-lite@sha256:7dc5f2fb50e1876a22ffcbed437621878e81172f6b8ea7d661cb201a01511908
        ports:
        - containerPort: 8080
        env:
        - name: DOCKER_ENABLE_SECURITY
          value: "true"
        resources:
          requests:
            cpu: 0m
            memory: 0Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
