apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirlingpdf
  labels:
    app: stirlingpdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stirlingpdf
  template:
    metadata:
      labels:
        app: stirlingpdf
    spec:
      containers:
      - name: stirlingpdf
        image: ghcr.io/stirling-tools/stirling-pdf:2.4.1-ultra-lite@sha256:5771c76b03aba6d445f67937e5f84c10ee03db1c259d3d1508fc9396328d1f0d
        ports:
        - containerPort: 8080
        env:
        - name: DOCKER_ENABLE_SECURITY
          value: "true"
        resources:
          requests:
            cpu: 0m
            memory: 0Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
