apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
- issuer.yaml
- api-token-sops.yaml
- webhook/repository.yaml
- webhook/release.yaml
- webhook/network-policy.yaml
- yewolf-fr.yaml
- hackcorp-net.yaml
- uctf-io.yaml
- management-prod-01-clusters-uctf-io.yaml
- reference-grant.yaml
