apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scrutiny
  namespace: scrutiny
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path-home1-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scrutiny-influxdb
  namespace: scrutiny
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path-home1-retain
