apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: scrutiny-config
stringData:
    scrutiny.yaml: ENC[AES256_GCM,data:NTx6Op1Bu8mLCexOqyCDEBnSAk2wzTMTiZ5BmpJdaaecQG7tJN5WjvBQ434IsimyUXhGvv+tqdu5qmFdvTbwPyOpuka37pq4ayG0dxvcWiqdFUpqrj1SZyfd+LUJor1Sc/o8aclA69xvYZ+9X4dWr22p4QzUBNvaJT+7K0KnbF+RlBDsOsKYn/vlIyOUb0ewgYlZnoprQilrw+qI+zyKEifpBw5R7oh9w5x88oilGjGWH7ZM0rGIpp4uE/nOV2dfstHrnyZ4lfhm/vUrrK1ymCJi/HI/9QVZaMy9AZceyRozn5KhzmZwzLEhq+y/KO5LxMmE6YN3cA0wutM+ELrr+/U5Z09ZL1iUmLt2YDaiJtNO3LrRY9CMDnCWq6rODoPG196605T6bqh5I8ezOKgI25OErHqm4DCXALplof4vFTmGEBB+S7NPYhxmkpW8SzQViau8x8MHKzjSqe6IzM49CRWLd4P33sP+MopIYHR2wbqCYMjGo1ETHZZiO0AsrQzgH4ip9EAacr48Qv5Rmt08lB70VA/BscfP0z/uL3oWUfYVsfzbwSj84pZmssmXymr9TXusYCeCWS427CnWHVFotyCvGhdAEctPv8c=,iv:j+b5x/Qz8ZK4Oyh3SfBjyolFhnS8PsYVZ6GzNfG9AwQ=,tag:yGhJ8OxVTAkok9KYCOa+dQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-05-16T19:29:28Z"
    mac: ENC[AES256_GCM,data:xrJVYSXq8jKPYBaWDW3m5M1AFaabBdXysO0fR8FOTGXORtXPbkuBsWWr6zoAfj6qsieviL1eYdaA+WnZrCOM3vK53a/Qn99gBKUWAUMbBv76lgTHsHImVewc4nAj39evzCguAILwjVWcA3WsElxd2IJ3CqxDfxS/dzJjw9xF4Lk=,iv:mSqdHFIonIopu+HWhOhpDpHfUfaEhgJ273QQBhujAE4=,tag:uWaysPxATtPUht4rrZkWjA==,type:str]
    pgp:
        - created_at: "2026-05-16T19:29:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC4LUCsV/V+wSAQdAYcFPMzWMcuc/eAN4w+VJONsOHUoVDM89srj+CLhxchYw
            M/SQgFF0aIH4ElWBmGC8oseNPp0WVkKQH6LNocEVBX5fFA6+ITpCXgd/fEfGnx5n
            0l4BqJ0WOFzyyKIs8q7fJEkq7IpYqu0XKDJqp2qBwMLGtKfr2CTT8ycBgVdOAJGO
            f33BEC/NKY9uCiudciTPa0gW8/XFB4iXNbBGS6fNFWYKQvZs3yX+ueX5ZvjLQaFt
            =azpV
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2026-05-16T19:29:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdAfs6cU61R5ZL+MxJDPQ0L3MuyZizoHbKKSTIR7rOv0kEw
            0dAMoiQrbFVXIB8Ty4vL5LyxmYnYP2+56bQnuXqgFVPVxUHfVSGIWKLUJzXUbJOw
            0l4B0KUfi6r6za1S9rRaiyd8bNHzUCs9Das6qZ5PkjsIREnGTivW6+4o1WUgvfQo
            E2BetxCEBO+x4Q/ziVIzHQIjGt+bly7dQ68tB4oU0P9wWT1VLIzHtgEJ2r/2mrgK
            =nbf8
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    version: 3.13.0
