apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustfs
  labels:
    app: rustfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rustfs
  template:
    metadata:
      labels:
        app: rustfs
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: rustfs
        image: mirror.gcr.io/rustfs/rustfs:latest@sha256:41fe89380f4120a337790c02af192c3fe7bb55c3edc2e6e9357b487b47c6ab21
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
          name: http
        - containerPort: 9001
          name: console
        env:
        - name: RUSTFS_CONSOLE_ENABLE
          value: "true"
        - name: RUSTFS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: rustfs-credentials
              key: root_user
        - name: RUSTFS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: rustfs-credentials
              key: root_password
        securityContext:
          runAsUser: 0
          runAsGroup: 2000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: 0m
            memory: 0Mi
          limits:
            cpu: 1000m
            memory: 512Mi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-rustfs-0
