apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: rustfs
spec:
  endpointSelector:
    matchLabels:
      app: rustfs
  ingress:
  - fromEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: envoy-gateway-system
    toPorts:
    - ports:
      - port: "9000"
        protocol: TCP
      - port: "9001"
        protocol: TCP
  egress:
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kube-system
        k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
      - port: "53"
        protocol: TCP
