apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: policy
spec:
  endpointSelector: {}
  ingress:
  - fromEntities:
    - host
  - fromEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kgateway
  - fromEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: tailscale
  - fromEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: mqtt
  - fromEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: dashboard
  - fromEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: home-assistant
    toPorts:
    - ports:
      - port: "1883"
        protocol: TCP
  - fromEntities:
    - world
    toPorts:
    - ports:
      - port: "8080"
        protocol: TCP
  egress:
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kube-system
        k8s-app: coredns
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
      - port: "53"
        protocol: TCP
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: home-assistant
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kgateway
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: authentik
        app: authentik-outpost
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: tailscale
        tailscale.com/parent-resource: dk1
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: mqtt
    toPorts:
    - ports:
      - port: "1883"
        protocol: TCP
  - toCIDRSet:
    - cidr: 0.0.0.0/0
      except:
      - 10.0.0.0/8
      - 192.168.0.0/16
