apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portfoliosh

resources:
- namespace.yaml
- hostkey-sops.yaml
- deployment.yaml
- service.yaml
- listenerset.yaml
- tcproute.yaml
- network-policy.yaml
