apiVersion: v1
kind: Service
metadata:
  name: portfoliosh
  labels:
    app: portfoliosh
    service: portfoliosh
spec:
  ports:
  - name: ssh
    port: 22
    targetPort: ssh
  selector:
    app: portfoliosh
