apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-system/
- infrastructure/cilium/ks.yaml
- infrastructure/gvisor/ks.yaml
- infrastructure/kata/ks.yaml
- infrastructure/longhorn/ks.yaml
- infrastructure/sysbox/ks.yaml
- platform/cert-manager/ks.yaml
- platform/descheduler/ks.yaml
- platform/certificates/ks.yaml
- platform/envoy-gateway/ks.yaml
- platform/external-dns/ks.yaml
- platform/external-secrets/ks.yaml
- platform/keda/ks.yaml
- platform/kyverno/ks.yaml
- platform/kyverno/policies/ks.yaml
- platform/metrics-server/ks.yaml
- platform/tailscale/ks.yaml
- platform/cnpg/ks.yaml
- platform/cnmsql/ks.yaml
- platform/barman-plugin/ks.yaml
- platform/postgres/ks.yaml
- platform/mysql/ks.yaml
- platform/talos-backup/ks.yaml
- platform/booting-up/ks.yaml
- platform/envoy-proxy/ks.yaml
- platform/postgres/applications/vaultwarden/ks.yaml
- platform/postgres/applications/umami/ks.yaml
- platform/postgres/applications/woodpecker/ks.yaml
- platform/postgres/applications/uctf/ks.yaml
- platform/postgres/applications/authentik/ks.yaml
- platform/postgres/applications/immich/ks.yaml
- platform/mysql/applications/uptime-kuma/ks.yaml
- apps/cyberchef/ks.yaml
- apps/dashboard/ks.yaml
- apps/radar/ks.yaml
- apps/portfolio/ks.yaml
- apps/portfoliosh/ks.yaml
- apps/capsule/ks.yaml
- apps/vaultwarden/ks.yaml
- apps/umami/ks.yaml
- apps/woodpecker/ks.yaml
- apps/home-assistant/storage/ks.yaml
- apps/home-assistant/ks.yaml
- apps/servarr/storage/ks.yaml
- apps/servarr/ks.yaml
- apps/immich/storage/ks.yaml
- apps/immich/ks.yaml
- apps/paperless/storage/ks.yaml
- apps/paperless/ks.yaml
- apps/uctf/ks.yaml
- apps/authentik/ks.yaml
- apps/rustfs/ks.yaml
- apps/registry/ks.yaml
- apps/scrutiny/ks.yaml
- apps/stalwart/ks.yaml
- apps/uptime-kuma/ks.yaml
- apps/webmail/ks.yaml
- apps/ytdlp/ks.yaml
