apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dawarich

resources:
- namespace.yaml
- secret-sops.yaml
- oidc-secret-sops.yaml
- pvc.yaml
- redis.yaml
- deployment.yaml
- service.yaml
- route.yaml
- network-policy.yaml
