apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: zones-hackcorp-net
  namespace: stalwart
spec:
  endpoints:
  - dnsName: v1-ed25519-20260730._domainkey.hackcorp.net
    recordType: TXT
    targets:
    - v=DKIM1; k=ed25519; h=sha256; p=Y7Wo24pwZIaq/YAvLWJAZgET2aWPOTq0gxDgJVdS88M=
  - dnsName: v1-rsa-20260730._domainkey.hackcorp.net
    recordType: TXT
    targets:
    - v=DKIM1; k=rsa; h=sha256; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4WZ1H9XXrEs+oMqrTlGsMYXiPEhbhO+Qzk3Btch5YWJLuZsGAPHNrL8AiRm8QdHOTZ1jWz/KgRiuWIx/+YZ8LPEEW0CJEFsjLnoipCbgKLax+BseKJPgwGzMI633bVmn5CxpdYAFFphVDGEWfXN+sS25qrhEy4gdPawHgRaz06xp7x9J8sIr/p4
    - wXEGxZX4sAx8ucr4B/5DCcVN966PuRrWDyFEarc/EZaBcub+X3edVOJhgp3UFPTop/rG3ayH8HzvCqlQ11KDflRPc7yLyrxnwAqvNlIl5vqoPUxOD2vUCgj8erAXfIR2pF2VuCrTfEagTKQJI43X1VMFglEFfWwIDAQAB
  - dnsName: hackcorp.net
    recordType: TXT
    targets:
    - v=spf1 mx -all
  - dnsName: hackcorp.net
    recordType: MX
    targets:
    - 10 mail.yewolf.fr
  - dnsName: _dmarc.hackcorp.net
    recordType: TXT
    targets:
    - v=DMARC1; p=reject; rua=mailto:[EMAIL]
  - dnsName: _caldavs._tcp.hackcorp.net
    recordType: SRV
    targets:
    - 0 1 443 mail.yewolf.fr.
  - dnsName: _carddavs._tcp.hackcorp.net
    recordType: SRV
    targets:
    - 0 1 443 mail.yewolf.fr.
  - dnsName: _imaps._tcp.hackcorp.net
    recordType: SRV
    targets:
    - 0 1 993 mail.yewolf.fr.
  - dnsName: _jmap._tcp.hackcorp.net
    recordType: SRV
    targets:
    - 0 1 443 mail.yewolf.fr.
  - dnsName: _pop3s._tcp.hackcorp.net
    recordType: SRV
    targets:
    - 0 1 995 mail.yewolf.fr.
  - dnsName: _submissions._tcp.hackcorp.net
    recordType: SRV
    targets:
    - 0 1 465 mail.yewolf.fr.
  - dnsName: mta-sts.hackcorp.net
    recordType: CNAME
    targets:
    - mail.yewolf.fr
  - dnsName: _mta-sts.hackcorp.net
    recordType: TXT
    targets:
    - v=STSv1; id=16876838626814041543
  - dnsName: _smtp._tls.hackcorp.net
    recordType: TXT
    targets:
    - v=TLSRPTv1; rua=mailto:[EMAIL]
  - dnsName: ua-auto-config.hackcorp.net
    recordType: CNAME
    targets:
    - mail.yewolf.fr
  - dnsName: _ua-auto-config.hackcorp.net
    recordType: TXT
    targets:
    - v=UAAC1; a=sha256; d=HrMnUXYdaimSXPa0nnbRkI5IZDQ4kyMuA99utsrMyyI=
  - dnsName: autoconfig.hackcorp.net
    recordType: CNAME
    targets:
    - mail.yewolf.fr
  - dnsName: autodiscover.hackcorp.net
    recordType: CNAME
    targets:
    - mail.yewolf.fr
