apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: mirror.gcr.io/phpmyadmin:5@sha256:f30eafced05930560bdb2394bee5a7dd847524e406205787025212e3dca49b9d
        securityContext:
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 80
        env:
        - name: PMA_ABSOLUTE_URI
          value: https://phpmyadmin.tail5ec535.ts.net
        - name: PMA_HOST
          value: mariadb
        startupProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 30
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
        resources:
          requests:
            cpu: 0m
            memory: 0Mi
          limits:
            cpu: 500m
            memory: 400Mi
