apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: mirror.gcr.io/phpmyadmin:5@sha256:27b329f0d1507d83a65ac0cd1465c33d9e82d37f04377be77c72cda2b15e808a
        ports:
        - containerPort: 80
        env:
        - name: PMA_ABSOLUTE_URI
          value: https://keda-phpmyadmin-ingress.tail5ec535.ts.net
        - name: PMA_HOST
          value: mariadb   # service name of your MariaDB instance
