apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: phpmyadmin
spec:
  hosts:
    - phpmyadmin.tail5ec535.ts.net
  pathPrefixes:
    - /
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: phpmyadmin
    service: phpmyadmin
    port: 80
  coldStartTimeoutFailoverRef:
    service: service-fallback
    port: 80
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 1500
