apiVersion: v1
kind: Secret
metadata:
    name: immich-db-credentials
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:xPP5UcC4,iv:ytpNnXW9wqBlZTqUUmOGIg4OfvBmm0Rtn9q3IIODaSg=,tag:4KCf/nn4A+T9EEBtzLGLCw==,type:str]
    password: ENC[AES256_GCM,data:LW7ZAxDLqtuacmIXrwrUiddxZNcobAD/p58UsxzpMtQ5qEiEOyMTo7Efp5M=,iv:Qu3G7i4lvKI/lQG8kWVn5Cy6vjhvVF1VCN7fRFu0NZs=,tag:Zx4xwOIknxHvKiATsnAI7w==,type:str]
sops:
    encrypted_regex: ^(data|stringData|secrets)$
    lastmodified: "2026-07-29T18:38:26Z"
    mac: ENC[AES256_GCM,data:f533gQnxnIht7NmuoWM8To8hkeZSDdaMqMYvFLyF584qe1rMPYb2i9+ajgUdJhVRKNANs2Gc0d4Sp3IMGgxo/ItaHgtAQCHFkN6vsgOSswPKi6xkxvyyISjh1qRHfM9zz8l4YI5qhmo7fRZTeDfp0zyYhi18d2YQ5oh+n4KkMyg=,iv:WGiicUVdztsoDYH5l3Ex58wU6OqXsU5xcr+osR6aIjA=,tag:LshG7fgratl5BvEH7/HOHg==,type:str]
    pgp:
        - created_at: "2026-07-29T18:38:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC4LUCsV/V+wSAQdAyuNHrliIZj9Ou/hWuiF9bpW3hS/47ns91hjECEOQqW8w
            9f5lOoVDKO/tEWTcPWfEIrPGgD/65XGeJM3uVvEM09bMZycKJugPhDosX9gr6Sac
            0l4BXna3JDxyeUbBzkN9UFOAeMj9qiqwtedTD0Ui6wt5lZoElpn5ZzY11fOqBhxo
            CBTcn1fA+zbVIjKQ+7Gg78glhVVdDjEyGua3AS9gDNcscewrExAPaInmD6kKjeAc
            =zTRP
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2026-07-29T18:38:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdAqMTodlrxbRri/hfjCSoJgR6bUjOXDwBtOL4kL/35ATMw
            vduNPTKvL1fRCLfJTI+V80h09mijqw+UB7CLkT2udPvy/fWlwgBfIRedrazB9rfy
            0l4BzqCtk2H5rlnA01U7cGxxjL5eCJZyB63zf/uRpGtID4Whtr8sTdvNE/i2YtpS
            3/IBxhAVbBlXRQ6KjXtWu46VP4ZYZQMtvbSmNrDVQx6z5oQrFxtzDDJvuj1//c3h
            =qmKr
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    version: 3.13.1
