apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uctf

resources:
- namespace.yaml
- network-policy.yaml
- ghcr-sops.yaml
- helm-repository.yaml

- safran
- basilic
- fenouil
