apiVersion: v1
kind: ConfigMap
metadata:
    name: immich-values
    namespace: immich
data:
    values.yaml: ENC[AES256_GCM,data:QH2mUOI8rYCDrT9JWhswQ6bDmJV+beZNPQEBqgcuVEstsmDdgFCe/IIF5cV4N/x0Rarfcy0NouBEVPG7s1aDHCdz8TjgbY5+7IxObmWWVAPrkQwb84mqIxCDfLgXmBV/nA8dG0HCS/GMHOEZMGprouhb/W1IQZL8BhChFEWLk7snKf0Yk+xQ+40s9FbtkoseXx2UIvCFW4sF06DvQAABl3fD0JfpcY2167Tvj/LVbAqSSvKyrYI91srco6xqjx4lPghGB+NiorfN6sBN/u1m70/NaUpk6tewCQ0nLvZTwlqnv4FId+fzIoz0oKnxIUSM1tChNBeGGZ5/m+WnM97iXnvaB0AO8qz0lAZk1UBjOdGL9duVZ3VS+Kfd3WlcaGiVway0ju1O+IflWZxKEA1lvyAGX0xqyX037Cu33DYYtfOZRTH5ou/h73HCb4tJcg9Fp29gii5ku68r8m00EFA43vBa3PglJUuT8Wlip6tJwT23K5eXjKp39Uf1bH+Ltt+bxrRzdaCOLSb8N+wgDqHI3MxxvP4YTtKmLtdQ7gKvXuISUDzsGzXimEYNlmY9Ci0FGmYieeylZlh7AWvHZetyu0Uz5D76pE55z6vcwYRNlt9nLa9S3fXxOuP9D1SNLhBL17u/bOH8/X648cYMZC2rbyzTDy3tu/CctGIPdcKi5RUCEDYj9nfrnOXQOS3HHVlMwZXE6yf4FG6TQ8IMMF806DJILukXDZvwxJuTjfnSp6CNQR0/5kvz7OENqCBdtktuQFrGhmepJnyBSP49D02zs2kmq1zncHXB6NETqHoxCykyxtAYyEkvQUJOprIx10L5A5OwOleWhnpABAskRxZ5tXDKmnGb3tXJpcgh8F308k6tshFKOf7GxTTUt0hNfuhi/Q1TyKIgdZOLcMMw76sYwP4+b/WnM9WofzxUpAm2GA9CuEYobQ0MN4GcubZ1XV1V8Cj/JqeSG/ba7lKKxrCbM/tDlRvwUrjWxnifMAdQa2Zm1WSHLu1lpmPhFCrJNKUp1Jh5Iic7hcESd9zYIue88wjUhMlwwPBQWMRe6WqO9vZ2m3NIleqJZY2fH3OJnOo=,iv:x6eFBUjSuNmWv+SbH3XZ4z1A41h/0yv9DbgJcXEqTDk=,tag:ve56q6Z+QeY1jfdYln6k3A==,type:str]
sops:
    lastmodified: "2026-03-23T17:46:00Z"
    mac: ENC[AES256_GCM,data:zfYMNHjN+ate4siJE8N0xcDG89T5iUCqNCkQKEz2DKec4BfEH5beK27PdDEboCjAa/5B6gX0h5+IjMI1pXxtLMFo55se/oeq7dlsGJ66COFEvljZsYxt2yRqr/eOtPU5XzRDEOTV574GJEg66bR7HwVLOOLVjcxfHqIti1JLFhA=,iv:NxaJh0J4ILZ340ujlcwNQW0NDOR4ssHur5OPEiINczE=,tag:gB6GDpRSNEbbguzVoYkAoA==,type:str]
    pgp:
        - created_at: "2025-09-03T10:06:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D6rJQTzBUCVESAQdA3f8Jq1fIFg3WZJuCMhRb//Gn7Zku99MtWoe8e39YPxQw
            NTmgfeexkeTJwkial0fcLvon9hAqOVxBN+kArThyBofqxvqXm+1VJ5syGnmEmxLr
            0l4B2/veZjvWp9ubAK264ccqEhnlr1Mm0i+croE4Q5xg7MyEM80O3e5E6/HJWkyf
            pfWOQSi+zl5jEy7VCKBLG7LG87pZ0I8m1JPfcI8SxdOhc3BFzVcGzLHtx9pL16lY
            =N068
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2025-09-03T10:06:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdAJDp/GskA6AzqMgcFv0EqGOgqX8YL42debcHwI8+srRgw
            WxA8bNKfJYvkvoGYkt3YfrV/nz+6ri/aYYHk8O4Nr+5cKNKet4N7wlro5xQyPmu4
            0l4BJ9j0Sh5ZQe9yAeX27FetbDPDZVXUzihhSrNbaNB3Cwi1y/0kAmibQxb4fCaY
            kSvOarg8zQbPLWA+kiatLzQ2yQH0RuWQKTO4x2mJ6QzxFL3N0Umz/EAp4MPUCxON
            =/CEp
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    encrypted_regex: ^(data|stringData|secrets)$
    version: 3.10.2
