apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberchef
  labels:
    app: cyberchef
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyberchef
  template:
    metadata:
      labels:
        app: cyberchef
    spec:
      containers:
        - name: cyberchef
          image: ghcr.io/gchq/cyberchef:11.0.0@sha256:4cb08716816d9eb92fdf1c0f5aa158872e305e912d2e8074b3dbdb041d3fb34f
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 0m
              memory: 0Mi
            limits:
              cpu: 200m
              memory: 100Mi
